### ISSUE TITLE
Support for Exceptions to be converted to response

### ISSUE THREAD

**Issue by sazzer** [graphql-java-kickstart/graphql-java-tools#100]
It would be very useful if this library could support something akin to the @ExceptionHandler mechanism in Spring MVC, allowing the resolver methods to throw an Exception and have this handled and converted into an actual response value to send back to the client.

Right now I have several resolvers that all do things similar to:
```
    fun saveUser(id: String, updated: String, details: UserInput) : Any {
        val userId = UserId(id)

        try {
            authorizationCheck.checkThrowing {
                isUser(userId)
            }

            val updated = userModifier.save(userId,
                    Instant.parse(updated),
                    UserData(
                            details.name,
                            details.email
                    ))
            return userModelTranslator.translate(updated)
        } catch (e: AuthorizationFailedException) {
            return GeneralErrorModel("UNAUTHORIZED",
                    "Not authorized to update user: $id")
        } catch (e: UnknownResourceException) {
            return GeneralErrorModel("UNKNOWN_USER",
                    "The requested user was unknown: $id")
        } catch (e: OptimisticLockFailureException) {
            return GeneralErrorModel("WRONG_UPDATED_TIME",
                    "The requested user has a different Updated timestamp to the one provided: $updated")
        }
    }
```

It would be much cleaner if, instead, I could do:
```
    fun saveUser(id: String, updated: String, details: UserInput) : Any {
        val userId = UserId(id)

            authorizationCheck.checkThrowing {
                isUser(userId)
            }

            val updated = userModifier.save(userId,
                    Instant.parse(updated),
                    UserData(
                            details.name,
                            details.email
                    ))
            return userModelTranslator.translate(updated)
    }

    @ExceptionHandler(AuthorizationFailedException::class)
    fun handleAuthorizationFailedException(e: AuthorizationFailedException) = 
        GeneralErrorModel("UNAUTHORIZED", "Not authorized to update user: $id")
```

I've no idea how to handle this and still be true to the GraphQL schema though.

**Comment by zhewang2** [comment]
Check this link https://github.com/graphql-java/graphql-java/blob/master/docs/execution.rst and see DataFetcherResult inside topic "Returning data and errors".

**Comment by oliemansm** [comment]
@sazzer I like the idea, but is this really the library to support this though? My own custom error handler is implemented by providing a Spring bean for [GraphQLErrorHandler](https://github.com/graphql-java/graphql-java-servlet/blob/master/src/main/java/graphql/servlet/GraphQLErrorHandler.java) of **graphql-java-servlet**.

Perhaps we could create such a custom `GraphQLErrorHandler` implementation in **graphql-spring-boot** that is configured by searching for those same annotations Spring uses for exception handling. What do you think?

**Comment by liqweed** [comment]
@oliemansm That's a great idea, I like it.

**Comment by oliemansm** [comment]
I've cloned the issue to the spring boot project to track there. See https://github.com/graphql-java-kickstart/graphql-spring-boot/issues/162.

**Comment by Thinkenterprise** [comment]
I try it and it works in java. The only thing that is not so nice that you have to give the component a name otherwise the application does not start. 

```java
@Component("com.thinkenterprise.resolver.query.RootQueryResolver")
public class RootQueryResolver implements GraphQLQueryResolver {

	private RouteRepository routeRepository;
	
	@Autowired
	public RootQueryResolver(RouteRepository routeRepository) {
		this.routeRepository=routeRepository;	
	}
	
	public List<Route> routes() {
		throw new RouteException("My Own Exception");
		//return routeRepository.findAll();
	} 

	@ExceptionHandler(RouteException.class)
	public GraphQLError exception(RouteException routeException) {
		return new RouteGraphQLError(routeException.getMessage());
	}
	

}
```
