### ISSUE TITLE
Usage of generic types for implementation of relay-compatible GraphQL API

### ISSUE THREAD

**Issue by victordombrovskiy** [graphql-java-kickstart/graphql-java-tools#114]
Seems like usage of generics is not supported by GraphQL Java Tools, because if I try to run the following code, it throws the following error:

```
import graphql.relay.Connection
import graphql.relay.SimpleListConnection

@Component
class QueryResolver(private val userService: UserService) : GraphQLQueryResolver {
    fun users(first: Int?, after: String, env: DataFetchingEnvironment): Connection<User> {
        return SimpleListConnection<User>(userService.filter(page, size)).get(env)
    }
}
```

> Caused by: com.coxautodev.graphql.tools.TypeClassMatcher$RawClassRequiredForGraphQLMappingException: Type graphql.relay.Connection<com.zimidy.api.layers.storage.entities.node.nodes.User> cannot be mapped to a GraphQL type!  Since GraphQL-Java deals with erased types at runtime, only non-parameterized classes can represent a GraphQL type.  This allows for reverse-lookup by java class in interfaces and union types.

Is there any way to make it working?

PS: Actually, my final goal is to expose a relay-compatible API.  Thus, if there are other ways to achieve this goal, I would be very appreciated if someone gave me a clue. 

---

I know, it is more question than issue. But I decided to post it here, because [a similar question](https://stackoverflow.com/questions/45844302/relay-based-pagination-in-java-for-java-graphql-server) already exists for about 4 months on StackOverflow and still no one answered it:

**Comment by tomasAlabes** [comment]
@victordombrovskiy were you able to solve this?

**Comment by oliemansm** [comment]
I've added a unit test `RelayConnectionSpec` to reproduce this issue. In `master` I've made the unit test with concrete classes to make it pass. This shows how you can use it currently, but with a lot of boilerplate. Add the fact you have to specify these types in your SDL and you've got a lot of duplication that needs to be improved.

In the branch `bugfix/114` I've kept the failing unit test. It still has the same boilerplate in the SDL, but the implementation uses the existing generic return types, which aren't supported. First attempt was to simply replace the `Class<*>` references with `Class<out Any>`.

Anybody with experience in this area and time to help out a bit to try and find a solution? Think the approach I was attempting is a bit too simple. @apottere Any thoughts from your end on this?

**Comment by b4eEX** [comment]
@oliemansm in that test with concrete types you create a concrete Connection with overriden `getEdges` returning concrete Edge implementation, like this:

```kotlin
List<UserEdge> getEdges() {
    this.edges
}
```
However, in Java I can't even compile this due to `List` being invariant and `UserEdge` not being considered a subtype of `Edge<User>`. Is there a way around this?

**Comment by oliemansm** [comment]
So you converted that test example into a Java version? Then I think you'd have to explicitly transform it. Something like:
```java
List<UserEdge> getEdges() {
  return this.edges.stream().map(UserEdge.class::cast).collect(Collectors.toList());
}
```

**Comment by b4eEX** [comment]
@oliemansm I've just translated it into Java verbatim, without any logic, to see if it compiles:

```java
public class Test {

    static class QueryResolver implements GraphQLQueryResolver {
        // fixme #114: desired return type to use: Connection<User>
        UserConnection users(int first, String after, DataFetchingEnvironment env) {
            return (UserConnection) new SimpleListConnection<User>(new ArrayList()).get(env);
        }
    }

    // fixme #114: remove this implementation
    static class UserConnection extends DefaultConnection<User> {

        UserConnection(List<Edge<User>> edges, PageInfo pageInfo) {
            super(edges, pageInfo);
        }

        public List<UserEdge> getEdges() {
            return null;
        }

        public PageInfo getPageInfo() {
            return null;
        }
    }

    // fixme #114: remove this implementation
    static class UserEdge extends DefaultEdge<User> {

        UserEdge(User node, ConnectionCursor cursor) {
            super(node, cursor);
        }

    }

    static class User {
        Long id;
        String name;
    }
}

```

The problem is that javac is not buying that `UserEdge <: Edge[User]`.

**Comment by oliemansm** [comment]
That's interesting. Just reproduced it. When you replace it with `List<Edge<User>>` it'll compile, but then the test fails again because it can't find `Edge<User>`. Making #114 more important again. Not sure what Groovy does that makes this config work in that case.

**Comment by b4eEX** [comment]
@oliemansm I guess the only thing left is ditching `graphql.relay.*` entirely and manually coding all the relations. Except for `PageInfo`, maybe.

**Comment by oliemansm** [comment]
At the moment, yes. Which is terrible. Would really like to find a better solution for this, but that'll have to be developed as well. Not sure what your own timeline is. If it's something you need right now, then manually coding them sounds like the way to go.

#179 was looking for a solution for this problem as well. I was thinking if directives could help in this area. If you could add something like `@Connection` to a type which would automatically create this structure with `Connection<User>` and `Edge<User>`. That would maximally reduce the amount of boilerplate you would have to write I think. Maybe this could be implemented as a specific **graphql-java-tools** directive for supporting relay.

**Comment by oliemansm** [comment]
Ah, of course, renaming the method to `edges()` instead of `getEdges()` helps. Then you could still simply do though.

```java
public List<UserEdge> edges() {
            return super.getEdges().stream()
                    .map(UserEdge.class::cast)
                    .collect(Collectors.toList());
        }
```

**Comment by silencecorner** [comment]
@oliemansm unfortunately! the code would  throw an exception: `java.lang.ClassCastException: Cannot cast graphql.relay.DefaultEdge to com.coxautodev.graphql.tools.example.resolvers.Query$UserEdge`
```java
 public List<UserEdge> edges() {
    return getEdges().stream()
            .map(UserEdge.class::cast)
            .collect(Collectors.toList());
}
```

**Comment by oliemansm** [comment]
I've reworked the generics part to support generics and extended the unit test demonstrating its usage for supporting relay. See branch [bugfix/114](https://github.com/graphql-java/graphql-java-tools/tree/bugfix/114). I'll clean it up a bit before I'll actually merge it with `master`.

Keep in mind that this only addresses the fact that you had to define all those concrete classes. It does not address the need for having to define the types in the SDL. That's a separate enhancement that is raised in issue #179 as well, so I'll track that one there. Any suggestions/solutions you have in mind to implement that are welcome in that issue. I was thinking about a solution using directives, but have to investigate that more to see if that could indeed be a proper solution.

With this fix in place the code from the original post at the top should work. See unit test 
[RelayConnectionSpec](https://github.com/graphql-java/graphql-java-tools/blob/bugfix/114/src/test/groovy/com/coxautodev/graphql/tools/RelayConnectionSpec.groovy) in the bugfix branch for a working example.

**Comment by enriquedacostacambio** [comment]
@oliemansm you may want to update this test: https://github.com/graphql-java-kickstart/graphql-java-tools/blob/18eec212e83511c30c661745e66f7aca1e3b5242/src/test/java/com/coxautodev/graphql/tools/RelayConnectionTest.java#L23

**Comment by victordombrovskiy** [comment]
@oliemansm Do you know what version contains this changes? Support for this doesn't exists in 5.2.4, which is the latest version available via maven's central repository.

**Comment by oliemansm** [comment]
@victordombrovskiy  That's not the latest version, you probably need to upgrade your group id. See the badge on the readme which points to https://search.maven.org/artifact/com.graphql-java-kickstart/graphql-java-tools/5.4.1/jar

**Comment by victordombrovskiy** [comment]
@oliemansm To help you to understand my situation: I used concrete classes everywhere. Now I rewrote them to leverage generics. So, for example, instead of UserEdge and EventEdge I use Edge<User> and Edge<Event>. Similarly, instead of UserConnection and EventConnection I use Connection<T: User, Edge<T>> and Connection<T: Event, Edge<t>>.

**Comment by victordombrovskiy** [comment]
Thank you! Now everything works!
