### ISSUE TITLE
How to add a Directive?

### ISSUE THREAD

**Issue by crumhorn** [graphql-java-kickstart/graphql-java-tools#166]
In the documentation for graphql-java, they use RuntimeWiring to create a directive as:

`wiring.directive("directiveName", new SchemaDirectiveWiringImpl())`

The only way I see how to add a directive here is to create the GraphQlSchema object and then do a:

`GraphQLSchema newSchema = GraphQLSchema.newSchema(justCreatedSchema).additionalDirective(new SchemaDirectiveWiringImpl()).build();`

However, in that code, they don't take a SchemaDirectiveWiring interface as an argument, but a GraphQLDirective class, which seems to have zero possibility to actually convert an object from A to B as the data passed to it and methods available are just lacking. Also, if I go that route, my overridden methods don't actually get called anyway, no matter what I set.

So, is there a way to add a directive somehow or am I out of luck? I don't mind merging graphql-tools and graphql-java in some way when creating the schema but I can't seem to find a way to get my directive in there using graphql-java-tools (and I really don't want to use the normal way of declaring every data fetcher etc)

**Comment by CH-EricLundberg** [comment]
I would love to know how to get access to the underlaying graphql-java schema after it has been autowired by graphql-java-tools. Then I could tweak some stuff by hand that doesn't autowire well. Is there some kind of post construction hook?

**Comment by gipeshka** [comment]
As of what I've seen in the code I have a small question related to directives.
In schema parser [when creating an input object](https://github.com/graphql-java/graphql-java-tools/blob/master/src/main/kotlin/com/coxautodev/graphql/tools/SchemaParser.kt#L133) the field doesn't get the directives added, even though the `definition` contains all the required data. Why is that so?

@CH-EricLundberg I guess you can inject `GraphQLSchema`, it's wired via `GraphQLJavaToolsAutoConfiguration`

**Comment by oliemansm** [comment]
@crumhorn Not familiar with wiring and directives myself. Although those directives seem pretty useful at first glance. Looking at graphql-java-tools it creates the schema programmatically in `SchemaObjects` like this:
```kotlin
fun toSchema(): GraphQLSchema = GraphQLSchema.newSchema()
        .query(query)
        .mutation(mutation)
        .subscription(subscription)
        .build(dictionary)
```
This is the last step after parsing the SDL and it has created the necessary `GraphQLObjectType` objects.

When I look at the documentation of graphql-java, [especially about wiring](https://graphql-java.readthedocs.io/en/latest/schema.html#creating-a-schema-using-the-sdl), it seems to use an entirely different approach for creating the schema.

So either [graphql-java](https://github.com/graphql-java/graphql-java) would have to add support for the type of directives you need, or graphql-java-tools would have to use a different approach in creating the schema. I think that is some serious amount of work though.

**Comment by enriquedacostacambio** [comment]
maybe i'm missing something, but i think it would be great to have the option of using graphql-java-tools only as a graphql.schema.idl.WiringFactory that can then be combined with other wiring factories.
for example: to combine typed resolvers with generic fetchers, or to add directive wirings.

**Comment by oliemansm** [comment]
This will be available in 5.4. See https://www.graphql-java-kickstart.com/tools/directives/ for more details.

**Comment by alexgenco** [comment]
Any plans to add support for `ENUM_VALUE`? Our use case is to determine whether to convert enum values to all upcase depending on the version of the client making the request (for backwards compatibility).

**Comment by oliemansm** [comment]
Yeah, will take a look at it.

**Comment by oliemansm** [comment]
@alexgenco Will be available in 5.4.1.

**Comment by alexgenco** [comment]
@oliemansm thanks for doing this. Is there a way to override the datafetcher for an enum value at query execution time, like the documentation examples do for `FIELD_DEFINITION` directives? I'd like to use `DataFetcherFactories.wrapDataFetcher`, but the `GraphQLEnumValueDefinition` object doesn't expose it.

**Comment by oliemansm** [comment]
@alexgenco That's actually functionality from [graphql-java](https://github.com/graphql-java/graphql-java). Could you raise an issue over there how you should be handling this? Either on their github or through their Spectrum channel. I'm not sure what hook is available during query execution time for this type. And you probably don't want to have to add a directive to every location where you use the enum to handle it using the `FIELD_DEFINITION`.

**Comment by anatolyw** [comment]
After reading all above posts (especially this: [@oliemansm comment on Sep 1, 2018](#issuecomment-417840305)) and documentation (https://www.graphql-java-kickstart.com/tools/directives/) for me it is still not clear how `graphql-java-tools` performs directive processing. 

I would assume to have some "magic" done by `graphql-java-tools` when it finds implementation of SchemaDirectiveWiring interface (analog how it works with GraphQLQueryResolver or GraphQLSubscriptionResolver interfaces), but looks like define `public class UppercaseDirective implements SchemaDirectiveWiring {...}` (see documentation) is not enough.

So, **can anyone explain how to do a final magic by hands as it stay in documentation (see below snippet)?** Basically I need to add directive processing on top what `graphql-java-tools` does in `SchemaObjects.kt`. 
```
// Add our custom directive when creating the schema parser:
SchemaParser.newParser()
  .file("schema.graphqls")
  .directive("uppercase", new UppercaseDirective())
  // ...
  .build()
  .makeExecutableSchema();
```

Extra Note: my graphqls schema is big enough and split logically to many files in different directories.

Any help is very appreciated.

**Comment by bonobonohu** [comment]
i'm sure you found it meanwhile, but just for the record, the complete, working sample is here:
https://github.com/graphql-java-kickstart/samples/tree/master/directives

**Comment by lirugo** [comment]
> After reading all above posts (especially this: [@oliemansm comment on Sep 1, 2018](#issuecomment-417840305)) and documentation (https://www.graphql-java-kickstart.com/tools/directives/) for me it is still not clear how `graphql-java-tools` performs directive processing.
> 
> I would assume to have some "magic" done by `graphql-java-tools` when it finds implementation of SchemaDirectiveWiring interface (analog how it works with GraphQLQueryResolver or GraphQLSubscriptionResolver interfaces), but looks like define `public class UppercaseDirective implements SchemaDirectiveWiring {...}` (see documentation) is not enough.
> 
> So, **can anyone explain how to do a final magic by hands as it stay in documentation (see below snippet)?** Basically I need to add directive processing on top what `graphql-java-tools` does in `SchemaObjects.kt`.
> 
> ```
> // Add our custom directive when creating the schema parser:
> SchemaParser.newParser()
>   .file("schema.graphqls")
>   .directive("uppercase", new UppercaseDirective())
>   // ...
>   .build()
>   .makeExecutableSchema();
> ```
> 
> Extra Note: my graphqls schema is big enough and split logically to many files in different directories.
> 
> Any help is very appreciated.

i still have similar question

**Comment by NachoBorras** [comment]
I'm following the sample [here](https://github.com/graphql-java-kickstart/samples/tree/master/directives) and the documentation [here](https://www.graphql-java-kickstart.com/tools/directives/) and my uppercase directive is applied to all the fields, even if I don't tag any field for using it. So I would like a bit of clarification to the question above.

**Comment by meiblorn** [comment]
@NachoBorras , it seems you've made this wiring as a component. When it is declared as a spring component, it becomes global

**Comment by NachoBorras** [comment]
@meiblorn I don't remember the code from the time I did the question but I've tried now and for me has worked to follow ONLY the sample [about the directives](https://github.com/graphql-java-kickstart/samples/tree/master/directives). The way proposed in the [wiki](https://www.graphql-java-kickstart.com/tools/directives/) doesn't seem to work.

Anyway, thanks for answering @meiblorn since it has made me review this question, which I forgot :)
