### ISSUE TITLE
String-formatted schema descriptions not in introspection query

### ISSUE THREAD

**Issue by miriam** [graphql-java-kickstart/graphql-java-tools#169]
We use string-formatted descriptions in our schema, as per the current GraphQL [spec](https://github.com/facebook/graphql/pull/327). You can see an example [here](http://facebook.github.io/graphql/June2018/#sec-Descriptions).

When we migrated to graphql-java-tools, the schema descriptions disappeared from the introspection query. Changing our schema to use \# comment descriptions fixed this issue.

**Comment by oliemansm** [comment]
@miriam Can you check with version 5.4.0 (which uses graphql-java 11.0) the problem still occurs? The parsing of the SDL is handled by graphql-java. So if you still encounter this issue with version 11.0 of that library then please raise an issue over there: [graphql-java](https://github.com/graphql-java/graphql-java).

**Comment by hyunrealshadow** [comment]
I am using graphql-java 11.0 and graphql-java-tools 5.5.1.

https://github.com/graphql-java-kickstart/graphql-java-tools/blob/32428720ec97caf3100a98f24f1b297b68d19580/src/main/kotlin/com/coxautodev/graphql/tools/SchemaParser.kt#L64-L68

The current description is obtained by this method.
But if you use String-formatted schema descriptions, It will be in ObjectTypeDefinition.description.
https://github.com/graphql-java-kickstart/graphql-java-tools/blob/32428720ec97caf3100a98f24f1b297b68d19580/src/main/kotlin/com/coxautodev/graphql/tools/SchemaParser.kt#L137-L142
So this issue has nothing to do with graphql-java.
@oliemansm Is this issue likely to be fixed?
