### ISSUE TITLE
Mixing `.graphqls` and java types

### ISSUE THREAD

**Issue by tomasAlabes** [graphql-java-kickstart/graphql-java-tools#179]
Hi! First thanks for all the work done in the library!
In my case, I'd like to mix types from a `.graphqls` file and create other types programmatically (extending https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/relay/Connection.java in particular) and I can't find the way.

```kotlin
    @Bean
    fun schemaParser(): SchemaParser {
        return SchemaParser.newParser()
            .files("graphql/types.graphqls")
            .resolvers(typesQueriesResolver)
            .build()
    }
```

I tried with the dictionary option and injecting some other beans like `GraphQLSchema` or `SchemaParserOptions` but I got nowhere. 
It's actually related to #114 too.

Is it possible or is it a feature?

Thanks!

**Comment by tomasAlabes** [comment]
It's actually related to https://github.com/graphql-java/graphql-java-tools/issues/114 too

**Comment by oliemansm** [comment]
Without the need for writing the boilerplate type definitions you mean? There's currently no proper solution for this in place I believe. Thinking about this now as well seeing #114. Perhaps support for directives could help, although that seems to be for handling existing types, not dynamically adding new types. There's no way to configure custom directives either right now, see #166.

**Comment by tomasAlabes** [comment]
Yeah, I was actually trying to avoid creating the Connection in the SDL. When I couldn't, I added them and encountered the problem in #114. I'm not sure if mixing programmatic types with SDL is a good idea though but at the moment it seemed my way out.

Directives would be great to avoid repeating types like connections. I've seen this in [aws-amplify](https://github.com/aws-amplify/amplify-cli/blob/master/graphql-transform-tutorial.md#reference-documentation) and I really like the idea. But you're right, it relies on existing types.

I think #114 and #166 are much more important than this one, this is a feature that wouldn't solve either so... I'll leave it at your discretion.

Thanks for your time!

**Comment by oliemansm** [comment]
@tomasAlabes 
There is a way for this now using the [Type Definition Factory](https://www.graphql-java-kickstart.com/tools/type-definition-factory/). Actually, this particular use case regarding connections has been implemented using this new feature, see [Relay](https://www.graphql-java-kickstart.com/tools/relay/).
