### ISSUE TITLE
Disable schema introspection query

### ISSUE THREAD

**Issue by alexcibotari** [graphql-java-kickstart/graphql-java-tools#181]
Hello ,

Is there any possibility to disable GraphQL query? related to

query {
__type {
...
}
__schema {
...
}
}
For example if I would like to hide my schema and types for outside world.

**Comment by oliemansm** [comment]
See https://github.com/graphql-java/graphql-spring-boot/issues/124#issuecomment-424222202 for potential implementation

**Comment by oliemansm** [comment]
Available since [release 5.3.4](https://github.com/graphql-java-kickstart/graphql-java-tools/releases/tag/v5.3.4)
