### ISSUE TITLE
Documentation missing for: SchemaParserOptions.objectMapperProvider

### ISSUE THREAD

**Issue by JonathanIlk** [graphql-java-kickstart/graphql-java-tools#196]
The Readme.md contains documentation for the "objectMapperConfigurer" Option.

This Option does not exist anymore and has been replaced with
`val objectMapperProvider: PerFieldObjectMapperProvider`
which is not documented.

**Comment by vojtapol** [comment]
`objectMapperConfigurer` is still a valid option. Also, the README does not mention it anymore.
