### ISSUE TITLE
Question: Can I Ignore non existing fields instead of throwing error?

### ISSUE THREAD

**Issue by alkismavridis** [graphql-java-kickstart/graphql-java-tools#202]
Question: Is it possible that the library ignores fields that do not exist in the schema, but executes normally the rest of the query?
The current behaviour is to throw an error:
`Validation error of type FieldUndefined: Field 'hello' in type 'Query' is undefined"`

I would like to have the query run normally, with the unknown fields being ignored.
Is this possible?

My reason for wanting that:
I use multiple schemas in my backend (one per user role). Some fields exist only in the higher role's schema files.
My backend decides which schema to use, based on the current session.

Now, my frontend must decide which fields to send and which not to send.
And this is because, if I have a lower user role that includes fields not specified on its schema, the whole query will crash. This puts me in a situation that I have to write pretty much logic and string proccessing to build my query, including only the fields that I should.

The story becomes more complicated, because I fetch my user also with the same query, so I cannot know its role in advance.

It would be **really nice** if I could just include all the fields, and that my backend would just ignore the ones that are not present in the schema.

Is this somehow possible?
Thanks a lot!!

**Comment by oliemansm** [comment]
@alkismavridis This question is actually one for [graphql-java](https://github.com/graphql-java/graphql-java). This library only wraps that one which contains processing logic like that.
