### ISSUE TITLE
Is async query execution with default data fetchers supported?

### ISSUE THREAD

**Issue by rrva** [graphql-java-kickstart/graphql-java-tools#206]
The default query execution strategy in graphql-java for async execution, AsyncExecutionStrategy, relies on the data fetchers being asynchronous. Do the default data fetchers used by graph-java-tools support asynchronous fetching? It seems like MethodFieldResolverDataFetcher does not.

What is the recommended way to achieve async execution and still use MethodFieldResolverDataFetcher ? 

Should I use ExecutorServiceExecutionStrategy ?

Some comments about this in the README could be helpful to others as well.

**Comment by vojtapol** [comment]
`AsyncExecutionStrategy` executes data fetchers asynchronously but the data fetchers themselves can be both synchronous or asynchronous. To make the data fetcher asynchronous simply return `CompletableFuture<T>` and the strategy will make sure to wait on its completion.
