### ISSUE TITLE
Can't download the project with maven

### ISSUE THREAD

**Issue by aviadavretz** [graphql-java-kickstart/graphql-java-tools#214]
EDIT: Solved, solution in the next comment.

Hello,

I have this weird bug since vesion 5.4.0 where Maven doesn't detect the right dependencies for graphql-java-tools, especially for kotlin dependencies.

This is the output of dependency:tree on my project using graphql-java-tools 5.4.1, for some reason it thinks the dependency is kotlin 1.2.71 when its clearly not:

> +- com.graphql-java-kickstart:graphql-java-tools:jar:5.4.1:compile
|  +- org.jetbrains.kotlin:kotlin-stdlib:jar:1.2.71:compile
|  |  +- org.jetbrains.kotlin:kotlin-stdlib-common:jar:1.2.71:compile
|  |  \- org.jetbrains:annotations:jar:13.0:compile
|  +- org.jetbrains.kotlin:kotlin-reflect:jar:1.2.71:compile
|  +- org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:jar:1.0.1:compile
|  |  \- org.jetbrains.kotlinx:kotlinx-coroutines-core:jar:1.0.1:compile
|  |     \- org.jetbrains.kotlinx:kotlinx-coroutines-core-common:jar:1.0.1:compile
|  +- org.jetbrains.kotlinx:kotlinx-coroutines-reactive:jar:1.0.1:compile
|  |  \- org.reactivestreams:reactive-streams:jar:1.0.2:compile
|  +- com.graphql-java:graphql-java:jar:11.0:compile
|  |  \- org.antlr:antlr4-runtime:jar:4.7.1:compile
|  +- com.fasterxml.jackson.core:jackson-core:jar:2.9.7:compile
|  +- com.fasterxml.jackson.module:jackson-module-kotlin:jar:2.9.7:compile
|  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.9.7:compile
|  |  \- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.0:compile
|  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.9.7:compile
|  +- com.esotericsoftware:reflectasm:jar:1.11.7:compile
|  +- org.apache.commons:commons-lang3:jar:3.8.1:compile
|  +- com.google.guava:guava:jar:26.0-jre:compile
|  |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
|  |  +- org.checkerframework:checker-qual:jar:2.5.2:compile
|  |  +- com.google.errorprone:error_prone_annotations:jar:2.1.3:compile
|  |  +- com.google.j2objc:j2objc-annotations:jar:1.1:compile
|  |  \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.14:compile
|  \- org.slf4j:slf4j-api:jar:1.7.25:compile

 

I've tried deleting my local maven repository, invalidating IntelliJ caches, nothing works...
I know that probably this has nothing to do with this library but since it only happens to me with this one I thought you may help somehow..

These are my declared dependencies:

> 
    <dependencies>
        <dependency>
            <groupId>com.graphql-java-kickstart</groupId>
            <artifactId>graphql-java-tools</artifactId>
            <version>5.4.1</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-websocket</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
        </dependency>
        <dependency>
            <groupId>com.graphql-java-kickstart</groupId>
            <artifactId>graphql-spring-boot-starter</artifactId>
            <version>5.3.1</version>
        </dependency>
        <dependency>
            <groupId>com.graphql-java-kickstart</groupId>
            <artifactId>graphiql-spring-boot-starter</artifactId>
            <version>5.3.1</version>
        </dependency>
        <dependency>
            <groupId>com.graphql-java-kickstart</groupId>
            <artifactId>voyager-spring-boot-starter</artifactId>
            <version>5.3.1</version>
        </dependency>
        <dependency>
            <groupId>com.graphql-java</groupId>
            <artifactId>java-dataloader</artifactId>
            <version>2.2.0</version>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

**Comment by aviadavretz** [comment]
Solved: The problem came from spring-boot-dependencies project (v2.1.0), which has a property "kotlin.version" set to 1.2.71, I guess it didn't conflict for me until now...

Setting kotlin.version in my own project to 1.3.10 fixed the problem for me.

However it seems quite fragile, do you think there's something we can do with it?

**Comment by stevenbeeckman** [comment]
I just spent an hour or so googling for NoClassDefFoundException regarding Kotlin dispatchers etc. 

Adding `<kotlin.version>1.3.10</kotlin.version>` to the `<properties>` of my pom.xml did the trick.

Thank you!
