### ISSUE TITLE
Warning log: Schema type was defined but can never be accessed, and can be safely deleted: PageInfo

### ISSUE THREAD

**Issue by slisaasquatch** [graphql-java-kickstart/graphql-java-tools#215]
I'm getting this warning log with version 5.4.1:
```Schema type was defined but can never be accessed, and can be safely deleted: PageInfo```

**Comment by oliemansm** [comment]
Thanks for reporting. You can ignore the warning btw in this case.

**Comment by oliemansm** [comment]
That's why I kept this issue open as a reminder to remove it

**Comment by mizaoyu** [comment]
Can we please have this remove soon? Or is there any workaround to let it gone. It will be warned everytime there is a request coming in.

**Comment by kevcodez** [comment]
Any news?

**Comment by fabiocarvalho777** [comment]
Can we have this issue resolved soon please? I know it is harmless, but I see it's been here for a while. Thanks!!

**Comment by oliemansm** [comment]
This will be fixed in 5.6.1
