### ISSUE TITLE
How can I specify "extensions" in graphql resolvers?

### ISSUE THREAD

**Issue by bsara** [graphql-java-kickstart/graphql-java-tools#226]
In [the GraphQL spec](https://facebook.github.io/graphql/June2018/#sec-Response-Format), it talks about allowing an `extensions` property in the response as a sibling of `data` and `errors`:

> The response map may also contain an entry with key extensions. This entry, if set, must have a map as its value. This entry is reserved for implementors to extend the protocol however they see fit, and hence there are no additional restrictions on its contents.

**How is one supposed to utilize this using a query or mutation resolver?** I am aware of returning a `DataFetcherResult<T>` as being an option, but that only allows for `data` and `errors` to be specified, also, I'd prefer it if the libraries being used continue to take care of my `errors` generation since I know that it will be spec.

What I need to be able to do is specify either a warning or info message(s) along with the data that is returned (if any is returned...which very well could be the case with a mutation). The times that these messages are included will be conditional as well.

**Comment by bsara** [comment]
@oliemansm any word on this?

**Comment by vojtapol** [comment]
`DataFetcherResult` could probaby support. Please open the issue in https://github.com/graphql-java/graphql-java.
