### ISSUE TITLE
Kotlin Suspend functions, passing custom coroutine context

### ISSUE THREAD

**Issue by kubino** [graphql-java-kickstart/graphql-java-tools#230]
Dear authors. We would like to thank you for you effort on this fantastic library. We are using it with Kotlin coroutines functions and it works flawlessly. However we have some sort of issues when it comes to integrate libraries which are depending on ThreadLocal pattern. We have identified line where the coroutines are called: https://github.com/graphql-java-kickstart/graphql-java-tools/blob/master/src/main/kotlin/com/coxautodev/graphql/tools/MethodFieldResolver.kt#L159si  - as far we understood it , there  is no way to pass custom context.  Would be very helpfull to have some sort of hook, which can help us to modify(enhance - via TracingContextElement) the coroutine context based on Servlet Thread. Any thoughts would be appreciated

**Comment by kubino** [comment]
We did managed to get it working(Sleuth/Zipkin) via hard forking and doing something like this:

As found here https://github.com/openzipkin/brave/issues/820

```
val coroutineTraceCotext = environment.getContext<GraphQLContext>().httpServletRequest
                .get().getAttribute("__TRACE_CONTEXT")

        return if (isSuspendFunction) {
            var traceContext = options.coroutineContext
            if (coroutineTraceCotext is TraceContext) {
                traceContext += TracingContextElement(Tracing.current().currentTraceContext(), coroutineTraceCotext)
            }
            GlobalScope.future(traceContext) {
                methodAccess.invokeSuspend(source, methodIndex, args)?.transformWithGenericWrapper(environment)
            }

        } else {
            methodAccess.invoke(source, methodIndex, *args)?.transformWithGenericWrapper(environment)
        }
```

but this feels very hacky and some basic librabry support would be nice. We would be able to produce PR for this, but we are not sure what is the best way to implement it

**Comment by westd** [comment]
There doesn't appear to be a way in the current graphql tools to create the coroutine context when the coroutine is invoked.  In order to capture thread local state before the coroutine runs, some way is needed to create the coroutine context just before it's invoked.  

I changed the project this way:
When the coroutine is invoked changed it to use a coroutineContextProvider instead of coroutineContext:
return if (isSuspendFunction) {
            GlobalScope.future(options.coroutineContextProvider.provide()) {
                methodAccess.invokeSuspend(source, methodIndex, args)?.transformWithGenericWrapper(environment)
            }
        } else {
            methodAccess.invoke(source, methodIndex, *args)?.transformWithGenericWrapper(environment)
        }

the provider is defined like this:
interface CoroutineContextProvider {
	CoroutineContext provide();
}

and created as an extra parameter to SchemaParserOptions.  So it can be used like this:

@Bean
    fun schemaParserOptions(): SchemaParserOptions {
        return SchemaParserOptions.newOptions().coroutineContextProvider(TracingCoroutineContextProvider()).build()
    }

SchemaParserOptions still accept coroutineContext so it's backwards compatible

Would you accept a PR for this?

**Comment by oliemansm** [comment]
@westd That would be very much appreciated, thanks!

**Comment by westd** [comment]
Sorry the delay, PR here: https://github.com/graphql-java-kickstart/graphql-java-tools/pull/247

**Comment by jazart** [comment]
If I understand correctly, this would allow us to pass our own context so that ThreadLocal values such as SecurityContext can be propagated to coroutines? As of now, I'm losing my context authentication when calling suspend functions.

**Comment by westd** [comment]
Yes, the PR allows you to configure it something like this (this one propogates the sleuth trace/span id, you'd need something similar to propogate security context 

`@Configuration
class GraphQLConfig {

    @Bean
    fun schemaParserOptions(): SchemaParserOptions {
        return SchemaParserOptions.newOptions().coroutineContextProvider(TracingCoroutineContextProvider()).build()
    }

    private class TracingCoroutineContextProvider: CoroutineContextProvider {
        override fun provide(): CoroutineContext {
            return TracingContextElement()
        }
    }

    private class TracingContextElement : ThreadContextElement<CurrentTraceContext.Scope>, AbstractCoroutineContextElement(Key) {
        companion object Key : CoroutineContext.Key<TracingContextElement>

        val currentTraceContext = Tracing.current().currentTraceContext()
        val initial: TraceContext? = currentTraceContext.get()

        override fun updateThreadContext(context: CoroutineContext): CurrentTraceContext.Scope {
            return currentTraceContext.maybeScope(initial);
        }

        override fun restoreThreadContext(context: CoroutineContext, scope: CurrentTraceContext.Scope) {
            scope.close()
        }
    }

}`

**Comment by vojtapol** [comment]
Has been added in #247

**Comment by SenhorCastor** [comment]
Hi @jazart. I am facing similar issue with SecurityContext on authentication. Did you figure it out how to solve this problem?

thanks in advance
