### ISSUE TITLE
How to use Arrays in resolvers instead of Arraylist

### ISSUE THREAD

**Issue by snandesh** [graphql-java-kickstart/graphql-java-tools#234]
Actually, I already have made some resolvers wherein the arrays[] fields are defined.
Although when I created the schema for the same, for arrays, this project accepts only Arraylists.
Now I don't want to change my resolvers array type to arraylist.
Can you tell me a workaround wherein this project will accept arrays[] for arrays defined in schema.

**Comment by oliemansm** [comment]
Aren't the resolvers specific to this project anyway? Why don't you want to change to lists? 

There's no workaround that I can think of. If this project doesn't support arrays as you seem to have established, and you don't want to change the implementation of your resolvers to adhere to the required API of the project you only have the option to create a PR to add support for arrays to this project.

**Comment by snandesh** [comment]
I have used converted the REST swagger to GraphQL schema. Hence all the resolvers are already defined. I cannot change it to Arraylist now.
