### ISSUE TITLE
Record skipping/filtering

### ISSUE THREAD

**Issue by rrva** [graphql-java-kickstart/graphql-java-tools#235]
I want to implement a filter that can be applied to any field, which does not need to be explicitly defined on each field in the schema.

Either as a directive that can be passed in the query, or as a filter parameter, which is automatically added to each field.

I am looking for:

- Some way to hook into the execution of the default data fetchers, for example MethodFieldResolverDataFetcher to evaluate my filter before the field is fetched, and if the filter condition is false, return null. The filter expression is to be fetched either from a query directive or a field parameter
- If I go down the route of adding a filter parameter to each field, it would be useful to have some way to transform the schema and add a `filter: String` parameter to all fields programmatically

```
type Query {
  characters(): [Character]!
}

type Character {
  name: String!
  favoriteFood: Food!
}

type Food {
   name: String!
   cookingTimeMinutes: Int!
}
```

I could write a query like

```
{ 
    characters {
        name(filter: "Lando Calrissian")
        favoriteFood
    }
}
```

or

```
{ 
    characters {
        name @filter(expr: "Lando Calrissian")
     }
}
```

and also express the filter on any field level

```
{ 
    characters {
        name
        favoriteFood {
             name(filter: "Meatballs")
             cookingTimeMinutes
         }
     }
}
```

and the execution would only result in those Character values where the filter expression returns true
without expressing @filter or filter: on each field in the schema definition.

**Comment by oliemansm** [comment]
This sounds more like a question to ask in the [graphql-java](https://github.com/graphql-java/graphql-java) project instead. This project does not add features like that, but simply put only tries to map the schema to your objects. It relies completely on the functionality implemented by `graphql-java`.

**Comment by rrva** [comment]
com.coxautodev.graphql.tools.SchemaParser could maybe add a way to access graphql.schema.GraphQLSchema.transform so I could add a query parameter to all fields programmatically.

And it would be nice to be able to plug in my own generic data fetcher used for all fields without having to register one explicitly (to replace/wrap MethodFieldResolverDataFetcher etc)

**Comment by vojtapol** [comment]
You can access the `GraphQLSchema.transform` using `TypeDefinitionFactory`. It seems that you can only add whole types but you can actually modify the schema after it has been built by mutating the `existing: MutableList<Definition<*>>` input parameter.

Not the cleanest option but it works.
