### ISSUE TITLE
How to use Arrays in resolvers instead of Arraylist

### ISSUE THREAD

**Issue by snandesh** [graphql-java-kickstart/graphql-java-tools#239]
After days of digging I realized that the code for checking whether the resolvers have arraylists or something else is here:

TypeClassMatcher.kt : 
            is ListType -> {
                if (realType is ParameterizedType && isListType(realType, potentialMatch)) {
                    match(potentialMatch, graphQLType.type, realType.actualTypeArguments.first())
                } else {
                    throw error(potentialMatch, "Java class is not a List or generic type information was lost: $realType")
                }
            }

Can anyone tell me what should I change so as for the code to accept arrays instead of arraylists?

**Comment by oliemansm** [comment]
@snandesh I added a unit test and was able to reproduce and fix it based on that. This will be available in the next release. See changes in #245.

**Comment by snandesh** [comment]
Hi Michiel, its working. Thank you so much.

**Comment by asfernandes** [comment]
I'm found a problem with this part of code when using a list of a dynamic class inserted in the dictionary. How to make lists of dictionaries (`Map<String, Object>`) classes?
