### ISSUE TITLE
Exception with Multipart File Upload

### ISSUE THREAD

**Issue by jyangtj** [graphql-java-kickstart/graphql-java-tools#240]
Try to upload multiple files using mutation by following https://github.com/jaydenseric/graphql-multipart-request-spec.  It failed with the following exception.  Single file upload works fine.  Any suggestions?

No serializer found for class java.io.ByteArrayInputStream and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: java.util.ArrayList[0]->org.eclipse.jetty.util.MultiPartInputStreamParser$MultiPart["inputStream"])
java.lang.IllegalArgumentException: No serializer found for class java.io.ByteArrayInputStream and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: java.util.ArrayList[0]->org.eclipse.jetty.util.MultiPartInputStreamParser$MultiPart["inputStream"])
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3750)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3678)
	at com.coxautodev.graphql.tools.MethodFieldResolver$createDataFetcher$$inlined$forEachIndexed$lambda$1.invoke(MethodFieldResolver.kt:83)
	at com.coxautodev.graphql.tools.MethodFieldResolver$createDataFetcher$$inlined$forEachIndexed$lambda$1.invoke(MethodFieldResolver.kt:23)
	at com.coxautodev.graphql.tools.MethodFieldResolverDataFetcher.get(MethodFieldResolver.kt:156)
	at graphql.execution.instrumentation.dataloader.DataLoaderDispatcherInstrumentation.lambda$instrumentDataFetcher$0(DataLoaderDispatcherInstrumentation.java:86)
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:261)
	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:202)
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:70)
	at graphql.execution.Execution.executeOperation(Execution.java:159)
	at graphql.execution.Execution.execute(Execution.java:101)
	at graphql.GraphQL.execute(GraphQL.java:573)
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:515)
	at graphql.GraphQL.executeAsync(GraphQL.java:489)
	at graphql.GraphQL.execute(GraphQL.java:420)
	at graphql.servlet.GraphQLQueryInvoker.query(GraphQLQueryInvoker.java:95)
	at graphql.servlet.GraphQLQueryInvoker.query(GraphQLQueryInvoker.java:91)
	at graphql.servlet.GraphQLQueryInvoker.query(GraphQLQueryInvoker.java:42)

**Comment by ophelie** [comment]
I'm seeing this as well.

This is due to Jackson trying to serialize and deserialize `javax.servlet.http.Part` objects during value conversion triggered by the data fetcher.

Note that this is only happening when mapping parameters of type `List<Part>`; when mapping parameters of type `Part` everything works fine because Jackson fallbacks on a simple casting operation to convert the value, which it cannot do for generic types such as `List`. 

I managed to get my resolver working with this hacky workaround:
- To make the exception go away, declare a no-op custom Jackson serializer for `javax.servlet.http.Part`
- In the resolver's method, get the parts argument from the DataFetchingEnvironment; `environment.getArgument("files")`
- You still have to declare the parameter of type `List<Part>` in your method, but it's value will be empty

@oliemansm What is your recommendation to fix this problem ? In this case the jackson conversion is useless sine the list of part can directly be retrieved from the DataFetchingEnvironment.

**Comment by subham28** [comment]
Can you share the single file upload code. I am getting the same error in case of single file upload

**Comment by alexcibotari** [comment]
Hello ,

you can simply add **@JsonIgnore** annotation to your Part property

```
@JsonIgnore
private Part file;
```

in mutation check **DataFetchingEnvironment** 
```
  public Payload uploadFile(UploadFIleInput input, DataFetchingEnvironment environment) {
    LinkedHashMap<String, Object> ll = environment.getArgument("input");
    Part file = (Part) ll.get("file");
    input.setFile(file);
    return service.uploadFile(input);
  }
```

and it works with one file

**Comment by jakubbrodzinski** [comment]
Would you mind sharing working example with me? I get
`{"timestamp":"2019-05-19T16:31:05.151+0000","status":415,"error":"Unsupported Media Type","message":"Content type 'multipart/form-data;boundary=------------------------07182a3f39beb5b0;charset=UTF-8' not supported","path":"/graphql"}`  when I am using CURL to send file to my Mutation.

**Comment by jy19446** [comment]
Here is the sample code for single file upload:
Inside schema.graphql, add the following
`scalar Upload`
and
```
type Mutation {
testSingleFileUpload(file: Upload): UploadResult
}
```
Inside mutation resolver:
```
public UploadResult testSingleFileUpload(Part part, DataFetchingEnvironment env) {
   // use the part parameter to process the uploaded file
}
```
To test this, need to post these form data: 
```operations

**Comment by jy19446** [comment]
Here is the sample code for single file upload:
Inside schema.graphql, add the following
`scalar Upload`
```
type Mutation {
testSingleFileUpload(file: Upload): UploadResult
}
```
Inside mutation resolver
```
public UploadResult testSingleFileUpload(Part part, DataFetchingEnvironment env) {
   // use the part parameter to process the uploaded file
}
```
To test this, post the following form data (we use Postman) to GraphQL endpoint
**operations**
`{ "query": "mutation($file: Upload!) {testSingleFileUpload(file:$file){resultCode}}", "variables": {"file": null } }`
**map**
`{"file":  ["variables.file"]}`
**file** 
`chose your file`

**Comment by subham28** [comment]
Hi,

In the configuration file you have to add

import graphql.schema.GraphQLScalarType;
import graphql.servlet.ApolloScalars;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class FileUploadConfig
{
    @Bean
    GraphQLScalarType upload()
    {
        return ApolloScalars.Upload;
    }
}


and rest all is same as Jack Young code

**Comment by jy19446** [comment]
We are able to work around multi files upload issue based on ophelie's suggestion.

Create a no-op MultiPartSerializer, build the SchemaParserOptions and pass the options to SchemaParser

Inside schema.graphql, add mutation
```
testMultiFilesUpload(files: [Upload!]!): UploadResult
```

Inside mutation resolver
```
public UploadResult testMultiFilesUpload(List<Part> parts, DataFetchingEnvironment env) {
   // get file parts from DataFetchingEnvironment, the parts parameter is not used    
   List<Part> attchmentParts = env.getArgument("files");
    ...  
 }
```
Post the following form data to your graphql endpoint
**operations**
`{ "query": "mutation($files:[Upload!]!) {testMultiFilesUpload(files:$files){resultCode}}", "variables": {"files": [null, null] } }`
**map**
` { "file0": ["variables.files.0"] , "file1":["variables.files.1"]}`
**file0**
`your file`
**file1**
`your file`

**Comment by Ubisoft-potato** [comment]
@jyangtj can you get us more detail if your multipart file upload Java code about the javax.servlet.http.Part serialize
