### ISSUE TITLE
the root Query of schema can be broken into multiple querys with less fields?

### ISSUE THREAD

**Issue by weipinglee** [graphql-java-kickstart/graphql-java-tools#241]
This is not a big problem putting all the query fields into the root Query ,like this ,
type Query{
   user:User,
   product:Product,
   .... #many other fields
),
but it becomes difficult to manage these fields  as the project becoming more complicated and having more fields.Is there a good way to resolve this ? Break the root Query into multiple ones ,each is a root Query having respective  resolver class and spreads to multiple SDL files ，can this work?

**Comment by oliemansm** [comment]
Running into this one as well, would be nice to support.

**Comment by weipinglee** [comment]
Thanks for your reply!
The main reason for raising this question is it's easy to make confusion when the number of child fields in the Query or Mutation is increasing.I have resolved this in another  way,adding some fields in the root Query which is just to wrap a series of fields,these fields are similar to the controllers in the rest api  which contains some methods.
Like this,
type Query {
    series1:Series1,
    series2:Series2,
    ...
}
type Series1{
   user:User,
   users:[user],
   ...//other fields user-related
}

**Comment by weipinglee** [comment]
Now I write the root Query in another way  using extension types to add new fields to the top level schema “query”,so different groups of fields  can be placed in different schema files ,and respectively 
 these resolve methods of different groups can be placed in different java classes which implement the 
 interface of GraphQLQueryResolver.
This is a perfect solution.
