### ISSUE TITLE
TypeDefinitionFactory missing in release 5.2.4

### ISSUE THREAD

**Issue by etienne-sf** [graphql-java-kickstart/graphql-java-tools#255]
Hello,

 The TypeDefinitionFactory interface is missing in the graphql-java-tools-5.2.4.jar, available in the maven repository.

Here is the URL : 
http://central.maven.org/maven2/com/graphql-java/graphql-java-tools/5.2.4/graphql-java-tools-5.2.4.jar

Etienne

**Comment by graphql-java-gen** [comment]
Hello,

  I actually don't understand the link between the two graphql-java-tools : com.graphql-java and graphql-java-kickstart.

Both README.MD redirect to graphql-java-kickstart. At first, I thought I logged this ticket to a wrong URL. 
But the graphql-java-kickstart jar release is complete. Whereas the com.graphql-java lacks the TypeDefinitionFactory interface.

But it seems to be the correct URL.

Why do these two projects exist ?




Etienne

**Comment by oliemansm** [comment]
graphql-java is the old home of this project. It has been moved to graphql-java-kickstart last year. See this blog for details: https://www.graphql-java.com/blog/moving-projects/.

**Comment by graphql-java-gen** [comment]
Ok, thanks for the explanation.

I was a little puzzled that there could be two concurrent teams with the "same" project. It's better this way!    :)

In this blog, there is no word about graphiql-spring-boot-starter.

Can you confirm that it's the same story ?

Etienne
