### ISSUE TITLE
TypeResolverError: Expected object type with name 'Character' to implement interface 'Character', but it doesn't!

### ISSUE THREAD

**Issue by graphql-java-generator** [graphql-java-kickstart/graphql-java-tools#256]
Hello,

  I'm working on graphql-java-gen, a project which aims to generate the code to map GraphQL to a database, through java JPA.
It's available here :
https://github.com/graphql-java-gen/graphql-java-gen-project 

I'm facing an issue with the Character interface.

To use the spring data repositories, I need a Hero and a Droid entity, of course, like in the graphql-java-tools.
But I also need a Character JPA entity.

So I added a CharacterImpl JPA entity, which implements the Character interface.

But as soon as a Character entity (actually an instance of CharacterImpl) is returned I get the error in the title.
It can be from the hero query, or when querying the friends field from the human query.

How can I solve this error ?

This can be tested by using the above repository, and starting the GraphQLServer java program, in the graphql-maven-plugin-samples-StarWars-server.
It embeds a graphiql interface, available on port 8180.

Etienne

**Comment by oliemansm** [comment]
Hi Etienne,

Are you still facing this issue or were you able to solve it?

**Comment by etienne-sf** [comment]
I get back to code directly with graphql-java. It sill was not clear on how to solve it, but it's now running.

In clear : I didn't solve it, but I don't face it any more.

**Comment by etienne-sf** [comment]
(but I don't know how to close or cancel an issue here)

**Comment by MegaCookie** [comment]
It could be an issue where you didn't add all implemented classes to your `SchemaParserDictionary`

**Comment by etienne-sf** [comment]
I actually corrected the issue. But it was 6 months ago.

It's corrected now.
For those who are interested, it's in this project:
https://github.com/graphql-java-generator/graphql-maven-plugin-project

A wonderful plugin to help people using GraphQL with Java.
