### ISSUE TITLE
Default values for enum fields on input types not set correctly

### ISSUE THREAD

**Issue by skroll** [graphql-java-kickstart/graphql-java-tools#257]
It appears in the `SchemaParser#createInputObject` that the default value of input fields is not set to a proper value if it is an enum.

When the default value of a field on an input type is an enum, the parser is supplying an `EnumValue`, and it is being set, so when the schema metadata is retrieved, a `CoercingSerializeException` is thrown by graphql-java, since it can't do any comparison of `EnumValue.

https://github.com/graphql-java-kickstart/graphql-java-tools/blob/bdafe57e9dd47883cef9b0249421783fc7de95e8/src/main/kotlin/com/coxautodev/graphql/tools/SchemaParser.kt#L184-L204

However, further down the `SchemaParser`, the `createField` method uses the `buildDefaultValue` function for the default value. By simply changing `createInputObject` to use `buildDefaultValue`, this seems to fix it.

https://github.com/graphql-java-kickstart/graphql-java-tools/blob/bdafe57e9dd47883cef9b0249421783fc7de95e8/src/main/kotlin/com/coxautodev/graphql/tools/SchemaParser.kt#L283-L301

The issue tracks down to the `GraphQLEnumType`:

https://github.com/graphql-java/graphql-java/blob/8ba2d1da9a84d4490b59f59a43fb0d2f4d58a0f1/src/main/java/graphql/schema/GraphQLEnumType.java#L138-L162

The value being passed in ends up looking like `EnumValue{name='FOO'}`, which will never match, but by using `buildDefaultValue`, it turns it into the enum name, which the check will succeed.

All of this is may be moot point however, since it appears that `graphql-java` doesn't seem to support default values inside of input types (it gets coerced into a null value if is not present). However, I believe this is definitely a bug on the graphql-java-tools side.

What I'm not sure of is the possible complications of always using `buildDefaultValue(inputDefinition.defaultValue)`, if any.

**Comment by oliemansm** [comment]
Thanks @skroll, this is fixed in the next release.
