### ISSUE TITLE
Can't find graphql-java-tools in jcenter

### ISSUE THREAD

**Issue by SpearThruster** [graphql-java-kickstart/graphql-java-tools#258]
`find artifact com.graphql-java:graphql-java-tools:jar:5.4.0 in jcenter (https://jcenter.bintray.com/) -> [Help 1]
`
Why are there no releases from graphql-java-tools there? In the docs they will always be there.

**Comment by oliemansm** [comment]
Use the correct group id as specified in the readme

Groeten,
Michiel

________________________________
Van: Spase Markovski <notifications@github.com>
Verzonden: vrijdag, april 5, 2019 8:25 PM
Aan: graphql-java-kickstart/graphql-java-tools
CC: Subscribed
Onderwerp: [graphql-java-kickstart/graphql-java-tools] Can't find graphql-java-tools in jcenter (#258)


find artifact com.graphql-java:graphql-java-tools:jar:5.4.0 in jcenter (https://jcenter.bintray.com/) -> [Help 1]
Why are there no releases from graphql-java-tools there? In the docs they will always be there.

**Comment by SpearThruster** [comment]
Well now... thanks & sorry!
