### ISSUE TITLE
No method found with any of the following signatures

### ISSUE THREAD

**Issue by ychoufa** [graphql-java-kickstart/graphql-java-tools#260]
I added a new Schema for a CRUD of a entity. I implemented a class that implement GraphQLQuery and another GraphQLMutation.  When I start the server(spring boot), this is thown:

No method found with any of the following signatures (with or without one of [interface graphql.schema.DataFetchingEnvironment] as the last argument), in priority order:

I can't legaly show  the stack trace but it seems that the framework ignores the new class implementing GraphQlQuery and only look for the other classes implementing GraphlQLQuery and mutation

**Comment by mluis** [comment]
@ychoufa did you manage to solve it? I'm getting the same issue.

**Comment by ychoufa** [comment]
@mluis Did you solve your issue?
