### ISSUE TITLE
GraphQLCodeRegistry.Builder is null in custom SchemaDirectiveWirings

### ISSUE THREAD

**Issue by stieglma** [graphql-java-kickstart/graphql-java-tools#268]
Hi,

I recently tried to upgrade to the newest version of this library, (graphql-spring-boot-starter is now `5.8.1` and graphql-java-tools is now `5.6.0` both of them seem to be graphql-v12 so I think they should be compatible) and didn't find a solution for the new style of creating directives.

Consider this bean in my spring-boot configuration class:
```java
    @Bean
    public SchemaDirective isAuthorizedDirective() {
        return new SchemaDirective("isAuthorized", new IsAuthorizedDirectiveResolver());
    }
```
and the respective class:
```java
public class IsAuthorizedDirectiveResolver implements SchemaDirectiveWiring {

    @Override
    public GraphQLFieldDefinition onField(SchemaDirectiveWiringEnvironment<GraphQLFieldDefinition> env) {
        GraphQLFieldDefinition field = env.getElement();
        GraphQLFieldsContainer parent = env.getFieldsContainer();

        DataFetcher<?> originalDataFetcher = env.getCodeRegistry().getDataFetcher(parent, field);
        DataFetcher<?> authDataFetcher = dataFetchingEnvironment -> {
            Authentication auth = SecurityContextHolder.getContext().getAuthentication();
            if (auth instanceof JWTAuthentication) {
                return originalDataFetcher.get(dataFetchingEnvironment);
            }

            throw new UnauthorizedError();
        };

        // adding the authorized fetcher to the code registry builder
        env.getCodeRegistry().dataFetcher(parent, field, authDataFetcher);

        return field;
    }
}
```
On application startup I now run into nullpointer exceptions in the line `DataFetcher<?> originalDataFetcher = env.getCodeRegistry().getDataFetcher(parent, field);` because `getCodeRegistry` returns  null.

I debugged that now quite a while and the problem seems to be that in `DirectiveBehavior.toParameters` the conversion to `SchemaGeneratorDirectiveHelper.Parameters` only stores the runtime wiring, which is ignored while creating the `SchemaDirectiveWiringEnvironmentImpl`.

A solution could be to unpack the `GraphQLCodeRegistry.Builder` from the runtime-wiring, either at the first conversion from directive behavior parameters to schema generator parameters, or afterwards.

Maybe I do also only have to change how the directive is added?

**Comment by almyy** [comment]
I'm seeing the same issue, but in my case it's on an argument directive.

**Comment by b4eEX** [comment]
Seems to be caused by https://github.com/graphql-java-kickstart/graphql-java-tools/blob/master/src/main/kotlin/graphql/schema/idl/DirectiveBehavior.kt#L23, which was introduced in https://github.com/graphql-java-kickstart/graphql-java-tools/pull/262/

**Comment by b4eEX** [comment]
The culprit appears to be https://github.com/graphql-java-kickstart/graphql-java-tools/blob/master/src/main/kotlin/graphql/schema/idl/DirectiveBehavior.kt#L58, it explicitly passes `null` as `GraphQLCodeRegistry`.

**Comment by b4eEX** [comment]
So, this patch
```
Index: src/main/kotlin/graphql/schema/idl/DirectiveBehavior.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/main/kotlin/graphql/schema/idl/DirectiveBehavior.kt	(date 1555748287000)
+++ src/main/kotlin/graphql/schema/idl/DirectiveBehavior.kt	(date 1556633224000)
@@ -55,7 +55,8 @@
     }
 
     data class Params(val runtimeWiring: RuntimeWiring) {
-        internal fun toParameters() = SchemaGeneratorDirectiveHelper.Parameters(null, runtimeWiring, null, null)
+        internal fun toParameters() = SchemaGeneratorDirectiveHelper.Parameters(null, runtimeWiring, null,
+                GraphQLCodeRegistry.newCodeRegistry(runtimeWiring.codeRegistry))
     }
 
 }
```
works around the NPE, but I'm not really sure this is the right solution. I would guess that `Builder` is passed so that the directive could actually edit the code registry, and this solution does not support that.

**Comment by alexgenco** [comment]
FWIW this is still an issue with 5.6.0 + graphql-java 13.0.

**Comment by oliemansm** [comment]
Code registry builder is now more actively being used by the lib, so should be easy next step to fix this issue now. Will take a look
