### ISSUE TITLE
Possible type leaking when serializing java -> graphql

### ISSUE THREAD

**Issue by ieugen** [graphql-java-kickstart/graphql-java-tools#276]
Hi,

I came across some warning that I ended up fixing with a PR in graphql-java, however it turns out that the issue might be coming from this library. 

Could someone familiar with this code have a look and see if this is the case. I would like to push the fix upstream to any project. 

TL;DR: 
I got errors like `graphql.schema.CoercingSerializeException: Invalid input for Enum 'SortBy'. Unknown value 'EnumValue{name='createdOn'}'` . 

It seems that my fix - checking for `EnumValue` inside serialize might not be the right place to do it since graphql api should not reach that point. 

The two PR's and associated discussions are:
https://github.com/graphql-java/graphql-java/issues/1531 
https://github.com/graphql-java/graphql-java/pull/1533
https://github.com/graphql-java/graphql-java/pull/1532

**Comment by oliemansm** [comment]
Hi @ieugen,

Think I've found the solution for this one in 5.6.1. I've used the example schema from one of the related issues for the unit test which indeed resulted in some serialization error. That's what is fixed now, so should be good now.

**Comment by ieugen** [comment]
Thanks. I will update, check and come back with feedback if there are any issues.

Thanks.
