### ISSUE TITLE
Unable to match type definition (ListType{type=TypeName{name='INFAe'}}) with java type (interface java.util.List): Java class is not a List or generic type information was lost: interface java.util.List using Java Tools 5.6

### ISSUE THREAD

**Issue by luizvnasc** [graphql-java-kickstart/graphql-java-tools#277]
This error is in version 5.6.0 and java-graphql-servlet.
I tried with a custom class, a interface and a String as a generic type but all got the same error.
As I saw there are two issues that are similar to this one : #209 #208. 

```
type NFAe {
	id: ID!
	json: String
}

type Query {
	nfaes: [String]
}
```

```

@WebServlet("/graphql")
public class GraphQLEndpoint extends SimpleGraphQLHttpServlet {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private final String[] schemas = { "/schemas/nfae.graphql" };

	@EJB
	private RootResolver rootResolver;

	@Override
	protected GraphQLConfiguration getConfiguration() {
		return GraphQLConfiguration.with(createSchema()).build();
	}

	private GraphQLSchema createSchema() {
		return SchemaParser.newParser().files(schemas).resolvers(rootResolver).build().makeExecutableSchema();
	}

	

}


```
```
@Stateless
@LocalBean
public class RootResolver implements GraphQLQueryResolver {
	
	@Inject private NFAeService nfaeService; 
	
	public List<String> nfaes(){
		List<String> list =  new ArrayList<String>();
		list.add("um");
		list.add("dois");
		return list;
	}
	
}

```
```
UT005023: Exception handling request to /nfae/graphql: com.coxautodev.graphql.tools.SchemaClassScannerError: Unable to match type definition (ListType{type=TypeName{name='String'}}) with java type (interface java.util.List): Java class is not a List or generic type information was lost: interface java.util.List
```

**Comment by vojtapol** [comment]
Please try this in the latest version. I believe this has been fixed already. If it still does not work, please reopen the issue.

**Comment by huytin** [comment]
This problem happens because graphql-java-tools lib cannot handle EJB proxy. Define an EJBProxyHandler as below and pass it as an option of SchemaParser will solve the problem:

`import com.coxautodev.graphql.tools.GraphQLResolver;
import com.coxautodev.graphql.tools.ProxyHandler;

public class EJBProxyHandler implements ProxyHandler {
    @Override
    public boolean canHandle(GraphQLResolver<?> resolver) {
        return isEJBProxy(resolver);
    }

    @Override
    public Class<?> getTargetClass(GraphQLResolver<?> resolver) {
        return resolver.getClass().getSuperclass();
    }

    private boolean isEJBProxy(GraphQLResolver<?> resolver) {
        return resolver.getClass().getName().contains("$$$view");
    }
}`

`SchemaParser schemaParser = SchemaParser.newParser()
                .schemaString(sdl)
                .resolvers(resolvers)
                .options(
                        SchemaParserOptions.newOptions()
                                **.addProxyHandler(new EJBProxyHandler())**
                                .build())
                .scalars(scalars)
                .build();
        GraphQLSchema graphQLSchema = schemaParser.makeExecutableSchema();
        GraphQL graphQL = GraphQL.newGraphQL(graphQLSchema).build();`
