### ISSUE TITLE
Q:It is possible to convert Class to Schema?

### ISSUE THREAD

**Issue by namttdh** [graphql-java-kickstart/graphql-java-tools#279]
Hi, first sorry because my English very bad.
I have a question: how can i auto convert Class file from java to graphql schema.
I very comfortable working with graphql-java-tool but when my project scale up, it's maybe become burden, because i have exactly same property for both .class file and .graphql file. When i change property in .class file i also must do same thing in .graphql file, it's take a lot of time.Beside, i think object input should be auto generator schema(Mutation and Query no need) . So who have any idea for that? please share with me. Thank you

**Comment by oliemansm** [comment]
This project doesn't provide that feature. Maybe somebody else is working on some kind of schema generator for this atm, not sure. I'll leave it open for now to see if anybody  else might have any pointers for you, but if Google didn't help you till now you might consider writing such a generator yourself seeing it apparently annoys you so much ;)
