### ISSUE TITLE
How can I explicity declare interface implementations ?

### ISSUE THREAD

**Issue by Michel-Alves** [graphql-java-kickstart/graphql-java-tools#281]
Hi Guys, thanks for your effort to build a great lib here.

I hava a question: since [scan inplementarions](https://github.com/graphql-java-kickstart/graphql-java-tools/issues/117) not works anymore how can I explicity to declare implementations of a interface (or abstract class in my case) ? 

I try

```
SchemaParser.newParser()
            .file(SCHEMA_FILE)
            .directive("auth", AuthorizationDirective())
            .resolvers(query, mutation)
            .dictionary(Mokey::class.java, Bird::class.java)
            .build()
            .makeExecutableSchema()
```

For this schema:

```
interface Animal {
... fields
}

type Monkey implements Animal {
  ... fields
}

type Bird implements Animal {
   ... fields
}
```

And this classes: 

```
abstract class Animal : DomainEntity, Relatable

class Monkey : Anilmal()

class Bird: Animal()
```

and this dependencies:

 ```
   compile 'com.graphql-java:graphql-java:11.0'
    compile 'com.graphql-java-kickstart:graphql-java-tools:5.5.2'
```

But I get

>  "message": "Expected object type with name 'Unit' to implement interface 'Animal', but it doesn't!"

Quem I submit requests

**Comment by oliemansm** [comment]
@Michel-Alves Where does that 'Unit' come from all of a sudden? Because that's not part of your example schema and classes?

**Comment by LiorAzar** [comment]
Hi!
Any updates on that? 
Im also getting the same problem

The schema definition: 
```
interface GraphEntity {
    type : String
}


type Vertex  implements GraphEntity {
    type : String
    id : String
}

type Edge implements GraphEntity {
    type : String
}
```
And the class :
```
public abstract class GraphEntity {
    public abstract String getType();
}

@Data
@Component
public class Edge extends GraphEntity {
    private String type;

    @Override
    public String getType() {
        return type;
    }
}

@Data
@Component
public class Vertex extends GraphEntity {
    private String id;
    private String type;

    @Override
    public String getType() {
        return type;
    }
}
```
Error when starting the spring boot application
```
Object type 'Edge' implements a known interface, but no class could be found for that type name.
```

Using the latest version of grapql-java-tool 2.5.4

**Comment by oliemansm** [comment]
@LiorAzar The versions you're mentioning are not the latest versions of those libs. Make sure you use the correct group `graphql-java-kickstart`.

**Comment by vojtapol** [comment]
> "message": "Expected object type with name 'Unit' to implement interface 'Animal', but it doesn't!"

I think your resolver is returning `Unit` instead of `Monkey` or `Bird`. This could not be reproduced.
