### ISSUE TITLE
Java 11 Platform Module System, error: module graphql.java.tools reads package graphql.schema.idl from both graphql.java and graphql.java.tools

### ISSUE THREAD

**Issue by picodotdev** [graphql-java-kickstart/graphql-java-tools#282]
I'm trying to use **graphql-java-tools** dependency in a Java 11 project and the following Gradle configuration to include all dependencies in the module path.

```
compileJava {
    inputs.property("moduleName", moduleName)
    doFirst {
        options.compilerArgs = [
                '--module-path', classpath.asPath,
        ]
        classpath = files()
    }
}
```

On compilation time many line errors like these for a lot of project dependenciecies are echoed, finally the compilation fails.

```
error: the unnamed module reads package graphql.schema.idl from both graphql.java and graphql.java.tools
...
error: module graphql.java.tools reads package graphql.schema.idl from both graphql.java and graphql.java.tools
```

**graphql.schema.idl** package is provided by both **graphql-java** and **graphql-java-tools** what is not allowed in JPMS.

https://github.com/graphql-java/graphql-java/tree/master/src/main/java/graphql/schema/idl
https://github.com/graphql-java-kickstart/graphql-java-tools/tree/master/src/main/kotlin/graphql/schema/idl

**graphql-java-tools** package **graphql.schema.idl** only contains one class **DirectiveBehavior.kt**.

Is there any solution to resolve this package split?

**Comment by oliemansm** [comment]
Maybe there is since the recent updates of graphql-java, we'll have to check. The same package was needed because a public API was missing in graphql-java to hook into the directives, so this way we could access the package private helper class.

**Comment by oliemansm** [comment]
Created a PR for graphql-java to make that helper class public after they agreed they would accept that change. Once that's merged and released we can update this lib as well and this problem will be solved. Just have to wait for them to release first.

**Comment by ieugen** [comment]
Since the PR was merged, maybe this can be safely closed as well?

**Comment by hmeerlo** [comment]
Any update on this? Makes it hard to use in JDK8+ projects.

**Comment by oliemansm** [comment]
That PR is part of graphql-java 14.0 which hasn't been released yet unfortunately: https://github.com/graphql-java/graphql-java/milestone/25.

**Comment by picodotdev** [comment]
graphql-java 14.0 has been released. The changes in graphql-java-tools can be made to solve this issue.
