### ISSUE TITLE
guava coupling is quite loose

### ISSUE THREAD

**Issue by libetl** [graphql-java-kickstart/graphql-java-tools#283]
Hi there,

Is it worth removing the guava dependency ?
I have grep`ed com.google in the code and found this : 

```
$ grep -r "com.google" *
pom.xml:            <groupId>com.google.guava</groupId>
src/main/kotlin/com/coxautodev/graphql/tools/DictionaryTypeResolver.kt:import com.google.common.collect.BiMap
src/main/kotlin/com/coxautodev/graphql/tools/GenericType.kt:import com.google.common.primitives.Primitives
src/main/kotlin/com/coxautodev/graphql/tools/ScannedSchemaObjects.kt:import com.google.common.collect.BiMap
src/main/kotlin/com/coxautodev/graphql/tools/SchemaClassScanner.kt:import com.google.common.collect.BiMap
src/main/kotlin/com/coxautodev/graphql/tools/SchemaClassScanner.kt:import com.google.common.collect.HashBiMap
src/main/kotlin/com/coxautodev/graphql/tools/SchemaClassScanner.kt:import com.google.common.collect.Maps
src/main/kotlin/com/coxautodev/graphql/tools/SchemaParserBuilder.kt:import com.google.common.collect.BiMap
src/main/kotlin/com/coxautodev/graphql/tools/SchemaParserBuilder.kt:import com.google.common.collect.HashBiMap
src/main/kotlin/com/coxautodev/graphql/tools/SchemaParserBuilder.kt:import com.google.common.collect.Maps
```

maybe we can consider finding replacements with kotlin.

**Comment by libetl** [comment]
What is the purpose of the guice aop handler ? 
This is maybe why this dependency is mandatory, but I need to know more about it.

**Comment by oliemansm** [comment]
Hi,

Do you know of any proper Kotlin replacements for this?

**Comment by libetl** [comment]
Only homemade implementations for BiMap so far.

But BiMap is quite straightforward to write.

**Comment by libetl** [comment]
I could try to test without guava, if pull requests are welcome.

**Comment by oliemansm** [comment]
Pull requests are definitely welcome

Groeten,
Michiel
________________________________
Van: LiBe <notifications@github.com>
Verzonden: Wednesday, June 19, 2019 7:25:19 AM
Aan: graphql-java-kickstart/graphql-java-tools
CC: Michiel Oliemans; Comment
Onderwerp: Re: [graphql-java-kickstart/graphql-java-tools] guava coupling is quite loose (#283)


I could try to test without guava, if pull requests are welcome.

**Comment by oliemansm** [comment]
@libetl graphql-java-servlet which is used by graphql-spring-boot together with this lib uses guava as well. So not sure what the benefit would be for removing it from here, since in most cases it's simply just added again.

**Comment by libetl** [comment]
Ok thanks for the update. I think I am going to close it for now.
