### ISSUE TITLE
How to pass Params from GraphQLQueryResolver to GraphQLResolver

### ISSUE THREAD

**Issue by cybercoolsam** [graphql-java-kickstart/graphql-java-tools#286]
In GraphQlQueryResolver we recieve the params passed in the query , but I need to access those params in GraphQLResolver . When I try to get hold of params in GraphQLResolver using DataFetchingEnvironment it comes as null

    public class EmpResolver implements GraphQLResolver<Emp>{
	
	public List<Emp> getEmp(DataFetchingEnvironment env){
		
		String compId= env.getArgument("compId");

**Comment by oliemansm** [comment]
Did you take a look at the example project or documentation before asking this question? See https://github.com/graphql-java-kickstart/graphql-java-tools/blob/master/example/src/main/java/com/coxautodev/graphql/tools/example/resolvers/Query.java

You haven't shared your schema here, but it looks like a couple of things or wrong here, let's say your schema is:
```
type Query {
  emp: [Emp!]!
}
```
Then your class should be implementing the root resolver, not the specific resolver for `Emp`:
```java
public class EmpResolver implements GraphQLQueryResolver {
  public List<Emp> getEmp(String compId) {
    return //...
  }
}
```
So the argument is exposed as parameter on the method.

Also when you write a specific resolver for a type the first parameter needs to be the object. I suggest to play around with the example a bit first.

**Comment by cybercoolsam** [comment]
@oliemansm 

Following is My schema

type Emp {
  emp_id:Int
  emp_name: String
  emp_comp_id:String
}

type EmpPage {
    totalElements: Int
    totalPages: Int 
    currentPageNumber :Int
    emp:[Emp]
}

type Query {
empPageQuery(pageNumber:Int=0, emp_comp_id:String): EmpPage
}

**Comment by sanderploegsma** [comment]
I think this is a valid question, something that I'm struggling with as well. In my case I have the following schema:

``` graphql
type Query {
    category(slug: ID!, locale: Locale!): Category
}

enum Locale {
    EN_US
    EN_GB
    # ...
}

type Category {
    slug: ID!
    name: String
    products: [Product]
}

type Product {
    slug: ID!
    name: String
    # Rest of product fields
}
```

Now, when I'm querying a `Category` in a specific `Locale`, I need to also query `Product` using the same `Locale`. I tried:

- Adding the `Locale` parameter to the `CategoryResolver.products()` function, but that does not compile
- Adding the `DataFetchingEnvironment` parameter to the `CategoryResolver.products` and retrieving the `locale` parameter from there, but that yielded `null`

Since the docs don't mention cases like these, how am I supposed to tackle this?

**Comment by SuperJoran** [comment]
I have the same issue. My solution is less than optimal but is as follows:

- In the `GraphQLQueryResolver`, store the parameter as a variable: `dataFetchingEnvironment.getExecutionContext().getVariables().put("locale", locale);`
- In your `GraphQLResolver<Category>`, retrieve the variable: `dataFetchingEnvironment.getExecutionContext().getVariables().get("locale");`

I would really prefer to have access to the root-parameters in the `GraphQLResolver`

**Comment by oliemansm** [comment]
This is not a question for graphql-java-tools, but for graphql-java. See: https://github.com/graphql-java/graphql-java/releases/tag/v11.0. 

The top issue under "Other changes" says the following:

> #1269 - data fetchers can get their parents arguments
>
> Sometimes a child data fetcher wants to lookup upwards and know what arguments are passed to its parents. This is now supported via the ExecutionStepInfo class. You can get the parent ExecutionStepInfo from the current field ExecutionStepInfo and also gets its arguments.

So I'd try that. Otherwise you should ask the question in the https://github.com/graphql-java/graphql-java project.

**Comment by sanderploegsma** [comment]
Thanks for the tip, I might try that.

For now, I added the `locale` parameter to the `products` field: 

``` graphql
type Query {
    category(slug: ID!, locale: Locale!): Category
}

enum Locale {
    EN_US
    EN_GB
    # ...
}

type Category {
    slug: ID!
    name: String
    products(locale: String!): [Product]
}

type Product {
    slug: ID!
    name: String
    # Rest of product fields
}
```

This is a bit of a hassle in queries, but it works:

``` graphql
query {
  category(slug: "category-slug", locale: EN_US) {
    products(locale: EN_US) {
      name
    }
  }
}
```

**Comment by SuperJoran** [comment]
Sorry for posting in the wrong place @oliemansm, but this is where I ended up by searching on Google. 

Thanks for the solution anyways! Just to conclude, in the example above the locale could be retrieved by calling `dataFetchingEnvironment.getExecutionStepInfo().getParent().getArguments().get("locale")` in the `GraphQLResolver`
