### ISSUE TITLE
Multipart single File upload graphiql input  

### ISSUE THREAD

**Issue by suneelkumar45** [graphql-java-kickstart/graphql-java-tools#288]
hi guys

I'm trying file upload using spring-boot graphql project. I have gone through the issue post https://github.com/graphql-java-kickstart/graphql-java-tools/issues/240 and added required files in my project. But I haven't got idea on how to test file upload functionality through graphiql from browser? 

below are the inclusions and implementation 

pom.xml : dependency added
----------------------------------

		<dependency>
		    <groupId>com.graphql-java-kickstart</groupId>
		    <artifactId>graphql-java-servlet</artifactId>
		    <version>7.5.0</version>
		</dependency>

GraphqlScalarType : bean added
-------------------------------------
@Bean
	GraphQLScalarType upload() {
	  return graphql.servlet.ApolloScalars.Upload
	}

graphqlInput : file input added
---------------------------------------
# Field type for Upload
scalar Upload

input FileInput {
    name: String!
    file: Upload!
}

graphqltype: file type added
------------------------------------
# Field type for Upload
scalar Upload

type File {
    name: String
    file: Upload
}

Mutation Resolver : added function
----------------------------------------
private Part file
	
	Boolean testSingleFileUpload(FileInput input, DataFetchingEnvironment environment) {
	// use the part parameter to process the uploaded file
		LinkedHashMap<String, Object> ll = environment.getArgument("input");
		Part file = (Part) ll.get("file");
		println "testSingleFileUpload :: file :: ${file}"
                 //code to store the file data
	}

schema
-----------------------------
    # file upload 
	testSingleFileUpload(input: FileInput): Boolean

graphiql input: in browser
-----------------------------------
http://localhost:8080/graphiql

mutation {
  testSingleFileUpload(input: {name:"test", file: <how do we pass the file??>
  })
??? response??
}

any help here appreciated !!

Thanks
Suneel

**Comment by jyangtj** [comment]
I do not think that GraphiQL or GraphQL Playground support file upload.  We used Postman to test this.

**Comment by vojtapol** [comment]
GraphiQL does not support uploading files. You can open an issue in that project.

**Comment by rogeraime** [comment]
Hi,
 someone here know how to write a operations's query in Multipart using Insomnia for testing? I write my own but did not work and I received : 
{
  "timestamp": 1602774721435,
  "status": 422,
  "error": "Unprocessable Entity",
  "message": "",
  "path": "/graphql"
`}
hier is my query : 
{
  "query": "mutation ($numberPlate: String, $country: $String, $file: Upload) {createTicket(numberPlate: $numberPlate, country:  $country, file: $file)}{ id, timestamp}",
  "variables": {
    "numberPlate": "33333",
    "country": "xyz",
    "file": null
  }
}
Thk you in advance!

![att1](https://user-images.githubusercontent.com/61559462/96225350-3e9bbb00-0f91-11eb-81af-6ae029419f87.PNG)
![att2](https://user-images.githubusercontent.com/61559462/96225361-4196ab80-0f91-11eb-94b2-0c20d1a43aa0.PNG)
