### ISSUE TITLE
[Question] Is it possible to get the queried fields?

### ISSUE THREAD

**Issue by LybrialsGit** [graphql-java-kickstart/graphql-java-tools#292]
Can we somehow get the fields which are getting queried from the `GraphQLQueryResolver`?
We need to aggregate additional data for the response but if certain fields are not 
queried we dont need to aggregate the additional data for those fields.

**Comment by oliemansm** [comment]
So you want to determine which fields in your schema are actually not being used and can be removed? That's not something this lib provides.

**Comment by LybrialsGit** [comment]
I mean something like this: https://stackoverflow.com/questions/48004805/how-to-get-requested-fields-inside-graphql-resolver

In graphql-js resolvers expose an info field which contains all the fields which got requested.

**Comment by oliemansm** [comment]
There is an additional optional argument [DataFetchingEnvironment](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/schema/DataFetchingEnvironment.java) that contains additional info. This lib wraps [graphql-java](https://github.com/graphql-java/graphql-java), so best to ask those guys in this case.

**Comment by LybrialsGit** [comment]
thx
