### ISSUE TITLE
How to manually add resolvers in SpringBoot

### ISSUE THREAD

**Issue by igr** [graphql-java-kickstart/graphql-java-tools#293]
I have a bunch of `graphqls` definitions. I would like to manually add all method that will be resolvers instead of having ClassScanner search for it.

How can I do that in SpringBoot app?

**Comment by zhuravskiy** [comment]
Have same issue, we using graph ql in the large java app, and we have degradation of the app startup, because SchemaClassScanner too slow.

**Comment by AllirionX** [comment]
I think you can overrides the schemaParser Bean to provide your own resolvers.
```
@Configuration
public class GraphQLConfig {

    @Autowired
    AutowiredResolver1 autowiredResolver1;

    @Autowired
    AutowiredResolver2 autowiredResolver2;
    
    ...
    
    @Bean
    public SchemaParser schemaParser() {
        return SchemaParser.newParser()
                .file("my-schema.graphqls")
                .options(SchemaParserOptions.newBuilder().preferGraphQLResolver(true).build()
                .resolvers(autowiredResolver,autowiredResolver2,...)
                .build();
    }
}
```
Syntax to check as I am writing it without a compiler.

**Comment by vojtapol** [comment]
Please comment if @AllirionX did not answer your question.
