### ISSUE TITLE
Absence of Optional arguments are represented with Optional.empty() instead of null

### ISSUE THREAD

**Issue by asfernandes** [graphql-java-kickstart/graphql-java-tools#294]
Accordingly to graphql/graphql-spec#83 there is a distinction of null and absence of value in fields and arguments.

In graphql-java (using with the spring boot package) an Optional field respects that, i.e., absence sets the field to Java null and GraphQL null sets the field to Optional.empty().

However, in method arguments absence of value sets the Optional argument to Optional.empty(), not allowing to distinguish it from explicit GraphQL null.

**Comment by asfernandes** [comment]
The issue was originally created in https://github.com/graphql-java/graphql-java/issues/1586

**Comment by vojtapol** [comment]
This was a surprise to us too. The workaround is to pass in `DataFetchingEnvironment` and then call `DataFetchingEnvironment::containsArgument`.
