### ISSUE TITLE
How to execute resolvers in specified order

### ISSUE THREAD

**Issue by zenonwch** [graphql-java-kickstart/graphql-java-tools#296]
```java
1. @Data
2. @Builder
3. @NoArgsConstructor
4. @AllArgsConstructor
5. class User {
6.   private Long id;
7.   private String name;
8.   private int age;
9.   private boolean hasDriverLicense;
10. }
11. 
12. class UserResolver implements GraphQLResolver<User> {
13. 
14.   @Autowired
15.   private UserRepo userRepo;
16. 
17.   public String name (User user) {
18.     User persistedUser = userRepo.findById(user.getId());
19.     return persistedUser.getName();
20.   }
21. 
22.   public int age(User user) {
23.     User persistedUser = userRepo.findById(user.getId());
24.     user.setAge(persistedUser.getAge());
25.     return persistedUser.getAge();
26.   }
27. 
28.   public boolean hasDriverLicense(User user) {
29.     if (age(user) < 14) {
30.        return false;
31.     }
32.     User persistedUser = userRepo.findById(user.getId());
33.     return persistedUser.isHasDriverLicense();
34.   }
35. }
```
If I execute the following query - the age(User user) method is invoked twice:

```
query {
  user {
    hasDriverLicense
    name
    age
  }
}
```

How can I avoid this situation (how can I mark that the age field is already resolved)?
And is it possible to resolve one field within another field resolving method?
Or is it possible to set resolving order for the fields?

**Comment by mxmlnglt** [comment]
Maybe because you're not supposed to do this? i.e. call a resolver method from another resolver method?
Also I don't think these resolver methods were supposed to modifiy the DataInstance that was passed to them like here line 24:

    user.setAge(persistedUser.getAge());

**Comment by zenonwch** [comment]
@mxmlnglt if I use 
```java
public boolean hasDriverLicense(User user) {
    if (user.getAge < 14) {
        return false;
    }
    User persistedUser = userRepo.findById(user.getId());
    return persistedUser.isHasDriverLicense();
}
```
the method always return false, because the user does not have age yet.

And my question was: how to avoid such a situation. I don't want to execute the resolver's method twice, but I want to use the result of one resolver method in another one no matter the order of the queried parameters.

**Comment by vojtapol** [comment]
There is no support for this in this library and it won't be added. I would strongly recommend against mutating root objects during resolution.
