### ISSUE TITLE
Use directive to validate input object fields

### ISSUE THREAD

**Issue by almyy** [graphql-java-kickstart/graphql-java-tools#297]
I'm trying to create a directive that should, on an input object field, validate an input value at runtime. For example:

```
input Foo {
    bar: String @notBlank
}
```
I've tried to follow the same idea as the examples [here](https://github.com/graphql-java-kickstart/samples/blob/master/directives/src/main/java/directives/UppercaseDirective.java), but there's no datafetcher to wrap, since we don't have any `fieldsContainer` or `fieldDefinition`.

Is this currently possible, and if so, could you point me in the right direction?

**Comment by AllirionX** [comment]
You want to use [graphql-java-extended-validation](https://github.com/graphql-java/graphql-java-extended-validation), that is not yet perfectly compatible with graphql-java-kickstart. 
You will need to overwrite the Graphql configuration (Cliedeman published an example here https://gist.github.com/cliedeman/21b0c943f6c5138c3a68c070cf1fb847).

You will then run into a few problems I ran into in the last few days (both have workarounds):

- [SchemaParser.determineType does not determine input types as GraphQLInputObjectType](https://github.com/graphql-java-kickstart/graphql-java-tools/issues/321#issue-505279141)
- [Input Validation](https://github.com/graphql-java/graphql-java-extended-validation/issues/6)

**Comment by vojtapol** [comment]
Please comment on this issue if the question has not been answered.

**Comment by brendamckenne** [comment]
An issue is open at 
https://github.com/graphql-java/graphql-java-extended-validation/issues/12

actually its an issue with @NotBlank in that extended validation library

**Comment by alirezatali** [comment]
this is always happened when user directive on a field in an input object. in SchemaDirectiveWiring class and onInputObjectField method the environment.getFieldDefinistion and FieldContainer always null then we can not change datafetcher. or even can not get original datafetcher
