### ISSUE TITLE
Customize the calls made to GraphQLResolver methods

### ISSUE THREAD

**Issue by pedroviniv** [graphql-java-kickstart/graphql-java-tools#301]
Thank you for developing such a great tool for building graphql applications with Spring, I started using a few days ago and I'm really enjoying it.

But I think it would be nice if we could customize the calls made to GraphQLQueryResolver methods. 

For instance, with reflections api, I build a tool that scans for BatchLoaders implementations, automatically creates the DataLoaders and registers each of these in a DataLoaderRegistry. My motivation was avoid the boilerplate code for creating/registering each Data Loader at a time in GraphQLContextBuilder.

This works fine but it would be awesome If I could customize the calls made to the GraphQLResolver methods in order to detect and directly pass DataLoader instances to the method. This feature would avoid the necessity of manually get the reference to the DataFetchingEnvironment, calling getContext(), casting to GraphQLContext, calling getDataLoaderRegistry... and finally get the DataLoader by the registered name.

In order to resolve the N+1 query problem, the dataloader is a really handy tool and I think features like the one I commented above would enhance the productivity and simplicity of implementing batch calls.

Thank you and sorry If I wasn't clear, my english isn't really good.

**Comment by vojtapol** [comment]
`DataFetchingEnvironment` is a catch-all object that is supposed to solve all these issues. If you want to pass something more than the default, just add it to your custom `GraphQLContext`. 

In our project we did something similar with auto-generating data loaders and we fetch them by class, not string. Example usage:

```java
public CompletableFuture<Offer> rooftop(Customer customer, DataFetchingEnvironment environment) {
    GraphQLContext context = environment.getContext();
    return context.loadById(customer.getOfferId(), Offer.class);
}
```

Where `loadById` is responsible for looking up the correct `DataLoader` and returning the `CompletableFuture` for that offer ID.
