### ISSUE TITLE
Using SSE instead of websocket for graphql subscriptions?

### ISSUE THREAD

**Issue by jmfayard** [graphql-java-kickstart/graphql-java-tools#303]
Hello,
I implemented GraphQL subscriptions and I was amazed how simple elegant it was. Thanks!

What I wonder though is whether it's possible to use server sent events instead of websocket for the transport channel as recommended by this article
https://www.smashingmagazine.com/2018/02/sse-websockets-data-flow-http2/

**Comment by vojtapol** [comment]
Subscriptions are mostly implemented in https://github.com/graphql-java/graphql-java.

They are protocol-agnostic. The only contract you need to fulfill is that your data fetcher must return `org.reactivestreams.Publisher<T>`. How you implement the transport layer is up to you.

**Comment by miador** [comment]
Mr. @jmfayard do you have the project as open source? I'd like to see that implementation over SSE if possible.

**Comment by jmfayard** [comment]
No it's not open-source, sorry
