### ISSUE TITLE
How to return an error and data at the same time for the same field.

### ISSUE THREAD

**Issue by CH-EricLundberg** [graphql-java-kickstart/graphql-java-tools#311]
Previously I could get the ExecutionContext from the DataFetchingEnvironment and add an error to that, while at the same time continuing to return an object as expected.  This seems to have gone away, what is the preferred method to return and error and data for the same field? 

Example use would be the error is "Operation performed on Stale Data" and the data would then be the fresh data for the UI to consume.

**Comment by CH-EricLundberg** [comment]
I can return a DataFetchingResult with data and errors, but then the Errors from that are wrapped and seemingly serialized which really defeats the point since you can then not filter them or anything.  I feel I must be missing something.  Anyone have any suggestions?

**Comment by vojtapol** [comment]
`DataFetchingResult` is what should be used in this case.

What do you mean by this?:
> since you can then not filter them or anything

**Comment by CH-EricLundberg** [comment]
If I extend DefaultGraphQLErrorHandler and provide  the method:  `protected List<GraphQLError> filterGraphQLErrors(List<GraphQLError> errors)` then I can not do instance of on the errors because the errors are all the same concrete type. At least that was the case when I checked this in sept.  It seemed like the underlying error that was passed backed in the DataFetchingResult is serialized instead of an object at that point.

**Comment by vojtapol** [comment]
That would be an issue with `graphql-java` then. `graphql-java-tools` just hooks up the data fetchers to methods. It does not perform any serialization on the return types.

Please open an issue in https://github.com/graphql-java/graphql-java
