### ISSUE TITLE
Exclude classes from parsing

### ISSUE THREAD

**Issue by morrowyn** [graphql-java-kickstart/graphql-java-tools#313]
Hi, 

I have two classes with the same name: Foo, but they reside in two different packages, api.Foo and domain.Foo.

How can I make sure that only api.Foo is used for the GraphQL parsing? I run into this error during startup: Two different classes used for type.

I know the quick fix is renaming the api.Foo to FooDto, but i rather not have dto postfixed

**Comment by AllirionX** [comment]
You can define your own dictionary like this:

```
@Configuration
public class GraphQLConfig {
  public SchemaParserDictionary schemaParserDictionary() {
    SchemaParserDictionary dictionary = new SchemaParserDictionary();
    dictionary.add("Foo",api.Foo.class);
    return dictionary;
  }
}
```

Syntax to be checked as I am writing this without a compiler.

**Comment by vojtapol** [comment]
Solution:

```java
SchemaParser.newParser()
            ...
            .dictionary("Foo", api.Foo.class)
            ...
```
