### ISSUE TITLE
How can I create and use fragment in schema?

### ISSUE THREAD

**Issue by straki** [graphql-java-kickstart/graphql-java-tools#317]
I have created type, fragment and query but I don't see how I can use that fragment in query
```
type Person {
    id: ID!
    name: String
    title: String
}
```
```
fragment simplePerson on Person {
    id
    name
}
```
```
extend Query {
    getPerson(id: ID): Person
}
```

How ever I try to use this fragment I get error that query is not valid. And if I try to get Person type not fragment It's good but if I export the schema I don't see fragment at all.

Any advice or example how can I use fragments?

**Comment by oliemansm** [comment]
This is a generic GraphQL issue, unrelated to this project. Please raise these kind of questions on Stackoverflow instead of over here.
