### ISSUE TITLE
Spring security integration

### ISSUE THREAD

**Issue by pula2000** [graphql-java-kickstart/graphql-java-tools#322]
Any ideas how can I configure some graphQL operations to be behind auth and some to not be like with REST and spring security?

**Comment by AllirionX** [comment]
I wanted the same features are you were looking for, and the implementation is in fact quite easy. I can't share my project with you as it's not ready for open-source yet, but you can:

- have a look at t[his tutorial](https://www.howtographql.com/graphql-java/5-authentication/) on how to implement authentication with graphql-java 
- have a look at this [graphql-spqr](https://github.com/Blacktoviche/springboot-graphql-sqqr-jwt-demo) implementation that uses the `@EnableGlobalMethodSecurity(prePostEnabled = true)` annotation to allow `@Preauthorize` in the `org.prime.graphql.security.config.WebSecurityConfig` config class. The graphql framework used is graphql-spqr, not graphql-java, but the Spring security part is the the same.

Have fun understanding all of this, I don't time to write a full tutorial right now!

**Comment by oliemansm** [comment]
@pula2000 Did that response help you along?

**Comment by pula2000** [comment]
Sort of. Had to implement a custom request matcher class for graphql by implementing a RequestMatcher interface.
