### ISSUE TITLE
Default values specified for Int field are passed in as BigInteger to Resolver

### ISSUE THREAD

**Issue by rsnayak** [graphql-java-kickstart/graphql-java-tools#344]
I'm running into an issue with a list of default Int values in my schema.  If I pass in a list of values as arguments in my query, they are passed in as Integers to my Resolver, however, if I don't specify any values in my query, the default values are sent in as BigIntegers resulting in cast exceptions.  Here is an example:

Here is my Venue Type:
```javascript
type Venue {
    venueId: ID!
    name: String!
    location: String!
    meetings(type: [Int] = [1,2,3,4,5,6,7,8,9,10]): [Meeting!]!
}
```
Meeting type
```javascript
type Meeting {
  meetingId: ID!
  subject: String
  type: Int
}
```
MyQuery
```javascript
{findVenues(hotelId: 512){
  venue{
    venueId,
    name,
    meetings(type:[1,2])   {
      meetingId,
      type
    }
  }
}}
```
if I specify type:[1,2], they are sent in Integers to the "getMeetings" method of my VenueResolver.  If I don't send in any values as in:
```javascript
{findVenues(hotelId: 512){
  venue{
    venueId,
    name,
    meetings  {
      meetingId,
      type
    }
  }
}}
```
The default type List is sent in as BigIntegers to my getMeetings method of my VenueResolver.    I could work around this by accepting the arguments as a csv and then parsing the argument, but it seems counterintuitive to pass in a csv when the field is an Int.  Can you please let me know what I'm doing wrong?

Thanks!
Raj

**Comment by roblovelock** [comment]
This looks to be related to how default values are built in [SchemaParser](https://github.com/graphql-java-kickstart/graphql-java-tools/blob/master/src/main/kotlin/graphql/kickstart/tools/SchemaParser.kt)

    private fun buildDefaultValue(value: Value<*>?): Any? {
        return when (value) {
            null -> null
            is IntValue -> value.value
            is FloatValue -> value.value
            is StringValue -> value.value
            is EnumValue -> value.name
            is BooleanValue -> value.isValue
            is ArrayValue -> value.values.map { buildDefaultValue(it) }
            is ObjectValue -> value.objectFields.associate { it.name to buildDefaultValue(it.value) }
            else -> throw SchemaError("Unrecognized default value: $value")
        }
    }

The [IntValue](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/language/IntValue.java) in graphql-java-tools uses BigInt.

When the argument is parsed it is uses the `parseLiteral` method in [Scalars.java](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/Scalars.java) to coerce the BigInteger to an Int. 

I believe the fix would be to alter the `SchemaParser` to do the same coercing

**Comment by vojtapol** [comment]
@roblovelock care to open a PR for this? Any help is welcome.

**Comment by mxmlnglt** [comment]
@roblovelock any news regarding this?

just came across the same issue again, and hoping this would be resolved in one way or another, esp. because the way scalars are handled by default in graphql-java have recently changed: https://github.com/graphql-java/graphql-java/releases/tag/v15.0
