### ISSUE TITLE
Upgrade graphql-java to version 14

### ISSUE THREAD

**Issue by vojtapol** [graphql-java-kickstart/graphql-java-tools#354]
`graphql-java` version 14 [has been released](https://github.com/graphql-java/graphql-java/releases/tag/v14.0).

It would be great if someone could upgrade the dependency and test that everything works.

**Comment by lburja** [comment]
I've created a pull request. 
I don't know Kotlin very well, so maybe there is a more elegant way to solve the compilation issue caused by graphql-java 14. In any case, the result works fine on a medium-large application.

**Comment by lburja** [comment]
Any timeline for merging this?
