### ISSUE TITLE
two package path, make me confused

### ISSUE THREAD

**Issue by guodage** [graphql-java-kickstart/graphql-java-tools#363]
source code's package path is `graphql.kickstart.tools`, in git tag `5.7.1`.
but dependency in maven central repo is `com.coxautodev.graphql.tools`, in version `5.7.1`.

something I was wrong?

**Comment by guodage** [comment]
my error.

master change package path after tag `5.7.1`.

**Comment by vojtapol** [comment]
See #360. The change will be in the next release.
