### ISSUE TITLE
graphql-java-tools:6.0.0 Breaks api

### ISSUE THREAD

**Issue by Korges** [graphql-java-kickstart/graphql-java-tools#366]
When I switched that library from 5.7.0 to 6.0.0 it looks like the /GraphQL API endpoint is no longer exposed. 
that import breaks everything:

import graphql.kickstart.tools.GraphQLQueryResolver;

response:
{
    "timestamp": "2020-02-23T18:37:28.467+0000",
    "status": 404,
    "error": "Not Found",
    "message": "No message available",
    "path": "/graphql"
}

The 5.7.0 is working fine:
import com.coxautodev.graphql.tools.GraphQLQueryResolver;

**Comment by vojtapol** [comment]
`graphql-java-tools` does not have any endpoints, if you are using the Spring Boot starter or the GraphQL servlet those have not been updated yet and you should not be setting the version of `graphql-java-tools` directly.
