### ISSUE TITLE
Migration guide available to migrate from 5,x,x to 6.x.x / Schemas do not get discovered anymore on 6.x.x

### ISSUE THREAD

**Issue by d4nyel** [graphql-java-kickstart/graphql-java-tools#370]
Hey there,
Is there any migration guide available to migrate from 5,x,x to 6.x.x?

I noticed that the package name has changed from com.coxautodev.graphql to graphql.kickstart
Further: after changing the version and the package imports it seems that the schema files *.graphqls do not get discovered anymore. Before the change to 6.x.x every *.graphqls file was discovered correctly and the query and mutation "endpoints" were available. After the change it seems that the schema files do not get resolved anymore. That leads to the problem that no mutation or query is available anymore.

PS:
Is there any real world example available for the DataLoader / BatchLoader?
Thanks!

**Comment by anoop4tech** [comment]
facing the same issue with **graphql-java-tools** version (6.0.0) and **graphiql-spring-boot-starter** version (6.0.1), schema no longer discoverable.

**Comment by vojtapol** [comment]
Please include your `pom.xml` or `build.gradle` files. You can leave out everything except any GraphQL dependencies.

**Comment by d4nyel** [comment]
@vojtapol do they not? I thought so. 
Before the version update
`        <dependency>
            <groupId>com.graphql-java-kickstart</groupId>
            <artifactId>graphql-spring-boot-starter</artifactId>
            <version>5.10.0</version>
        </dependency>
        <dependency>
            <groupId>com.graphql-java-kickstart</groupId>
            <artifactId>graphql-java-tools</artifactId>
            <version>5.7.1</version>
        </dependency>
        <dependency>
            <groupId>com.graphql-java-kickstart</groupId>
            <artifactId>graphiql-spring-boot-starter</artifactId>
            <version>5.10.0</version>
        </dependency>`

After the version update
`        <dependency>
            <groupId>com.graphql-java-kickstart</groupId>
            <artifactId>graphql-spring-boot-starter</artifactId>
            <version>6.0.1</version>
        </dependency>
        <dependency>
            <groupId>com.graphql-java-kickstart</groupId>
            <artifactId>graphql-java-tools</artifactId>
            <version>6.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.graphql-java-kickstart</groupId>
            <artifactId>graphiql-spring-boot-starter</artifactId>
            <version>6.0.1</version>
        </dependency>`

What I have noticed after the update to 6.x.x:
- Package names have changed, so I had to modify each class implementing `GraphQLMutationResolver ` , `GraphQLResolver<T>` or `GraphQLQueryResolver`
-  The schema files do not get discovered anymore. Before the update the Queries and Mutation were available under the specified endpoint path. After the update my application only returns a 404 for the corresponding endpoint in combination with a GraphQL Post

The reason for the update is that I would like to implement the BatchLoder / DataLoader to prevent a query for each GraphQL property to resolve.

**Comment by vojtapol** [comment]
You are posting this issue in the wrong project. The issue is already posted here: https://github.com/graphql-java-kickstart/graphql-spring-boot/issues/353

GraphQL Java Tools dependency should not be declared separately from the GraphQL Spring Boot dependency. It should be pulled as transitive dependency. That way the libraries will be always compatible.

Please feel free to add further comments to the linked issue.

**Comment by vojtapol** [comment]
You are posting this issue in the wrong project. The issue is already posted here: https://github.com/graphql-java-kickstart/graphql-spring-boot/issues/353

Let's continue there.
