### ISSUE TITLE
Resolve `node(id: ID!)`

### ISSUE THREAD

**Issue by aymanmoukhtar** [graphql-java-kickstart/graphql-java-tools#372]
Hi, am using `graphql-java-tools` and Kickstart `spring-boot-starter`  to auto configure my Query resolvers, and using a `schema.graphqls` file.

I am trying to add support for relay, and one of the requirements is to add support for node retrieval by id in the RootQuery. 
```
type Query {
  node(id: ID!): Node
}
```

Can you please help me with how to add a resolver for this field? Am kinda new to the whole thing. 

Thanks!

**Comment by rjburdish** [comment]
Hey Ayman, how were you able to solve this? I'm trying to do exactly the same but can't seem to find much documentation for relay support and graphql-java

**Comment by aymanmoukhtar** [comment]
@rjburdish Hey, unfortunately no, i closed it, as we ended up not using Relay at all, so wasn't needed anymore.
The documentation on Relay support is really coming out short, even on Relay itself.

**Comment by rjburdish** [comment]
Ah, yeah I've used Apollo in the past and was hoping to use Relay this time around but unfortunately we inherited the backend which is already using graphql-java. I'll probably try for another a day or so but based on the limited documentation we'll most likely end up going the Apollo route again

**Comment by juliuskrah** [comment]
I have a not so elegant implementation for `node(id: ID)` that you can find in this [repo.](https://github.com/juliuskrah/graphql-demo).

I have the following schema definition

```graphql
type Query {
  node(id: ID!): Node
}
```

This is implemented with Spring Boot, so I make heavy use of Beans to route to the correct type based on the Opaque ID:

```kotlin
interface NodeService {
    fun node(id: String): Mono<out Node>
}

@Service("Product")
class ProductService: NodeService {
    fun node(id: String): Mono<Product> {
      //
    }
}

@Controller
class NodeController(val nodeServices: Map<String, NodeService>) {

    @QueryMapping
    fun node(@Argument id: String): Mono<out Node> {
        val (node, actualId) = // extract Node type from id
        val nodeService = nodeServices[node] ?:
            return Mono.error(IllegalArgumentException())
        return nodeService.node(actualId)
    }

}
```
