### ISSUE TITLE
How can I setup rules for fields visibility ?

### ISSUE THREAD

**Issue by meiblorn** [graphql-java-kickstart/graphql-java-tools#373]
I want to set up field visibility rules for my fields. How can I do it?

I've noticed that I can create my own implementation of `SchemaParser`:
![image](https://user-images.githubusercontent.com/4069585/76545720-b2c62b80-64a3-11ea-8d7a-d58dad239a0a.png)

But when I started to override it, I've faced an issue. Ofc I don't want to write the whole logic from scratch, I want to extend existing `SchemaParser`: here I need to override the following method:
![image](https://user-images.githubusercontent.com/4069585/76546030-37b14500-64a4-11ea-84f5-b078e16d5eb0.png)
and `toSchema()`:
![image](https://user-images.githubusercontent.com/4069585/76546061-47c92480-64a4-11ea-88bf-fe4a01209e80.png)

And here I can tune visibility rules.

The problem is that one of the constructor arguments of SchemaParser is `internal`
![image](https://user-images.githubusercontent.com/4069585/76546163-734c0f00-64a4-11ea-8dca-d352df7ecb8d.png)

And I can't reference this object in my code.
![image](https://user-images.githubusercontent.com/4069585/76546262-9b3b7280-64a4-11ea-904d-0f61033a01d0.png)

How to deal with it?

**Comment by oliemansm** [comment]
@meiblorn What do you have in mind exactly regarding visibility rules? Do you intend to hide certain elements from the schema depending on the user or something?

You're welcome to create a PR for this.

**Comment by oliemansm** [comment]
I've added an option to set `GraphQLFieldVisibility` through `SchemaParserOptions`. 

See also: https://www.graphql-java.com/documentation/v12/fieldvisibility/.
