### ISSUE TITLE
Upgrade kotlin coroutines to 1.3.5 blocked by deprecated publish

### ISSUE THREAD

**Issue by oliemansm** [graphql-java-kickstart/graphql-java-tools#378]
See https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-reactive/kotlinx.coroutines.reactive/kotlinx.coroutines.-coroutine-scope/publish.html

**Comment by benmccann** [comment]
There's just one call to `publish` in the codebase: https://github.com/graphql-java-kickstart/graphql-java-tools/blob/62270b51013e77194ccdcc43a43f12c75e745ba0/src/main/kotlin/graphql/kickstart/tools/SchemaParserOptions.kt#L134
