### ISSUE TITLE
Allow CoroutineContextProvider use information from environment

### ISSUE THREAD

**Issue by yehormasalitin** [graphql-java-kickstart/graphql-java-tools#387]
Hi, currently we luckily have the ability to change **coroutine** context using **CoroutineContextProvider**, but there is a restriction we have working with it when we are trying to resolve `coroutine` for subfields, for example:

Schema:
```graphql
type Query {
 actor: Actor!
}
type Actor {
 movies: Movie!
}
type Movie {
 imdbScore: Float!
}
```
Request:
```graphql
{
 actor {
  movies {
   imdbScore
  }
 }
}
```

For this request, we need to resolve 3 parts:
**actor** in **QueryResolver**
**movies** in **ActorResolver**
**imdbScore** in **MovieResolver**

Let's say we have **suspend** for everything, so **actor/movies/imdbScore** are resolving asynchronously.

Now, the tricky part. We also have some **RequestContext**, for example, it contains some context information from the **Header**, for our example, let's use: **UserContext(userId: Int)**
So when a request comes we resolve headers and grab **userId**.

What we can do, it that we can define **UserContext** as the custom context for **DataFetchingEnvironment**. Also, we can define **UserContext** as **RequestScope** bean in spring.

The problem is that we cannot use **RequestScope** bean in our **suspend** functions, as **RequestScope** bean lives as part of the main thread, not coroutine.
And we don't really want to use **DataFetchingEnvironment** in each resolver as it requires us to pass it as a parameter to each function.

So what can we do? We can define our own custom **CoroutineContextProvider** for example:
```kotlin
@Component
class CustomCoroutineContextProvider(private val userContext: UserContext) : CoroutineContextProvider {
    override fun provide(): CoroutineContext {
        return UserContextElement(userContext.userId)
    }
}
```

and then, whenever we need our context, we can always access it via **coroutineContext**

But, it is not really working for the example I specified earlier, and we can check why if we go by it step by step.

1. **QueryResolver** trying to resolve **actor**, then from **main** thread, which has **userContext** we grab **userId**, and add it to the **CoroutineContext**, we are launching new coroutine with this context.
2. **ActorResolver** trying to resolve **movies**, but the problem is that on this stage **ActorResolver** is working already from **coroutine**, so we cannot access **userContext** any more, and we get an error.

What can we do in this case?

The example solution I see in this case is if `CoroutineContextProvider` had `provide` method which would use `DataFetchingEnvironment`, for example:

```java
public interface CoroutineContextProvider {
	CoroutineContext provide(DataFetchingEnvironment environment);
}
```
and then in `MethodFieldResolver`
```kotlin
environment.coroutineScope().future(options.coroutineContextProvider.provide(environment)) {
  methodAccess.invokeSuspend(source, methodIndex, args)?.transformWithGenericWrapper(environment)
}
```
Or we can pass just `DataFetchingEnvironment` context, not whole `environment`, the idea is that we will be able to use useful information in `environment` to create `coroutine` context, then our modified example would look like
```kotlin
@Component
class CustomCoroutineContextProvider : CoroutineContextProvider {
    override fun provide(environment: DataFetchingEnvironment): CoroutineContext {
        return UserContextElement(environment.getContext().userId)
    }
}
```
and because context in `DataFetchingEnvironment` is consistent for the whole request we will have consistent `CoroutineContext` for all coroutines, whether they were created from main thread or from coroutine itself.

Or maybe there is a better solution for that?

Thank you

**Comment by aymanmoukhtar** [comment]
@egormasalitin 
Any updates on this one? were you able to solve it somehow? am having the exact same issue.

**Comment by egormasalitin** [comment]
@aymanmoukhtar No updates on this one, unfortunately, so we don't use coroutines for now.

**Comment by rrva** [comment]
We use MDC and https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-slf4j/kotlinx.coroutines.slf4j/-m-d-c-context/ for providing some information to suspendable resolvers across threads

```
class MDCContextProvider: CoroutineContextProvider {

    override fun provide(): CoroutineContext {
        return MDCContext()
    }
}

val schema = SchemaParser
        .newParser().file("my-schema.graphqls")
        .options(SchemaParserOptions.newOptions()
        .coroutineContextProvider(MDCContextProvider()).build())
```
