### ISSUE TITLE
Best practices for handling optional arguments?

### ISSUE THREAD

**Issue by alexgenco** [graphql-java-kickstart/graphql-java-tools#388]
We just updated graphql-java-tools from 5.4.1 and the biggest change is around nullable input fields (I think caused by https://github.com/graphql-java-kickstart/graphql-java-tools/pull/315).

Previously, we were defining our resolver methods with `Optional<>` arguments for those that are nullable in the schema, e.g. `first` in 

```graphqls
customers(input: CustomerSearchInput!, first: Int): [Customer!]
```

... mapped to the following resolver method:

```java
public List<Customer> getCustomers(CustomerSearchInput input, Optional<Integer> first) { ... }
```

Previously, the `first` argument was `Optional.empty()` regardless of whether the client passed an explicit `first: null` or didn't pass the argument at all. However, now we are getting `null` when the client doesn't pass the argument, which requires us to handle both `null` and `Optional.empty` in all resolver methods with optional arguments.

Is there a way to opt-out of this new behavior? Or if not, a recommended way to unify handling of `null` and absence? e.g. in the object mapper configurer or something?

**Comment by vojtapol** [comment]
This was done so that it could be detected whether the client passed in a parameter or not. If you are not interested in the distinction, can you just use `Integer first` and do a simple `null` check on it?

**Comment by alexgenco** [comment]
@vojtapol this is what we've started doing (updating the arguments to the unwrapped type, and doing an `Optional.ofNullable` on it inside the method body), but it will be duplicated in a lot of places, almost all of which the distinction between null and absent isn't meaningful.

**Comment by alexgenco** [comment]
Another question... we already have a custom class that we use to differentiate null vs. absent called `Omissible`, which is basically a wrapper around `Optional<Optional<T>>`, so `Omissible.absent` == `Optional.empty`, `Omissible.null` == `Optional.of(Optional.empty)`, and `Omissible.of(value)` == `Optional.of(Optional.of(value))`. Is there a way to hook up the schema object mapper to deserialize nullable arguments into `Omissible`?

**Comment by vojtapol** [comment]
> @vojtapol this is what we've started doing (updating the arguments to the unwrapped type, and doing an Optional.ofNullable on it inside the method body), but it will be duplicated in a lot of places, almost all of which the distinction between null and absent isn't meaningful.

I think the right way to solve this would be to add a configuration option that changes how Optional behaves. The current behavior would be the default but you could switch it to the old behavior.


> also want to mention that we have been using a custom deserializer for our omissible class on the schema object mapper for a while now, and it works for deserializing input object fields into omissibles, but we're seeing now that it doesn't work for top level field arguments. It seems like it should work the same for both?

Can you show me how are you passing the custom deserializer? I don't need to see it's implementation, just how it's provided to GraphQL Java Tools.

**Comment by alexgenco** [comment]
> I think the right way to solve this would be to add a configuration option that changes how Optional behaves.

👍  to this, we definitely don't want to have to null check top level arguments, when input sub-fields just work.

> Can you show me how are you passing the custom deserializer?

```java
GraphQLSchema graphQLSchema = SchemaParser.newParser()
  ...
  .options(SchemaParserOptions.newOptions()
    .objectMapperConfigurer((mapper, context) -> {
      mapper.registerModule(new OmissibleModule());
    })
    .build())
.build()
.makeExecutableSchema();
```

`OmissibleModule` is basically

```java
public class OmissibleModule extends SimpleModule {
  public OmissibleModule() {
    addDeserializer(Omissible.class, new OmissibleDeserializer());
  }
}
```

**Comment by alexgenco** [comment]
Any thoughts on this? This is basically blocking us from upgrading to the latest version

**Comment by vojtapol** [comment]
I think we should find a more generic solution that allows mapping to any "maybe" types such as Arrow's Optional https://github.com/graphql-java-kickstart/graphql-java-tools/issues/371

**Comment by vojtapol** [comment]
#404 addresses the first half of this issue. Let me know if it would fix your issue.

> Another question... we already have a custom class that we use to differentiate null vs. absent called Omissible, which is basically a wrapper around Optional<Optional<T>>, so Omissible.absent == Optional.empty, Omissible.null == Optional.of(Optional.empty), and Omissible.of(value) == Optional.of(Optional.of(value)). Is there a way to hook up the schema object mapper to deserialize nullable arguments into Omissible?
> 
> Edit: also want to mention that we have been using a custom deserializer for our omissible class on the schema object mapper for a while now, and it works for deserializing input object fields into omissibles, but we're seeing now that it doesn't work for top level field arguments. It seems like it should work the same for both?

This doesn't work because types that are a GraphQL scalar bypass the object mapper. We might want to look into changing that.

**Comment by alexgenco** [comment]
@vojtapol any chance for a patch release in the near future?

**Comment by vojtapol** [comment]
Yeah. There is a chance for that. We are planning to make the input argument mapping a lot more flexible for users that need more customization.
