### ISSUE TITLE
Java Bean validation support

### ISSUE THREAD

**Issue by williamboman-pp** [graphql-java-kickstart/graphql-java-tools#399]
Hi! I can't seem to find a nice way to make Java Bean validation work nicely without having to explicitly call [`Validator#validate`](https://docs.oracle.com/javaee/7/api/javax/validation/Validator.html#validate-T-java.lang.Class...-) in the resolver functions themselves.

I'd love to be able to leverage the `@Valid` annotation to have graphql-java-tools automatically validate input objects for me. Is this within the scope of this library?

**Comment by benmccann** [comment]
I was thinking it'd be really nice to be able to use method validation annotations. This would probably require graphql-java-tools to [instantiate and run the validator](https://www.baeldung.com/javax-validation-method-constraints#3-programmatic-validation)
```
@Singleton
public class GetPost implements GraphQLQueryResolver {
  @Override
  public User getUser(@Size(min = 5, max = 200) @NotNull String firstName) {
    ...
  }
}
```

**Comment by williamboman-pp** [comment]
> I was thinking it'd be really nice to be able to use method validation annotations.

Yes! Good addition, I forgot about this use case.

> instantiate and run the validator

I'd love to be able to pass my own Validator object, so maybe via the `SchemaParserOptions.Builder` with a new `.validatorProvider(validatorProvider: PerFieldValidatorProvider)`?

**Comment by oliemansm** [comment]
Isn't using directives for this sufficient? https://github.com/graphql-java-kickstart/samples/tree/master/directives

There's also a validators library from the graphql-java guys. Last time I checked there was an issue with it in certain cases though, not sure if it's fixed now: https://github.com/graphql-java/graphql-java-extended-validation.

**Comment by williamboman-pp** [comment]
> Isn't using directives for this sufficient? [graphql-java-kickstart/samples:directives@`master`](https://github.com/graphql-java-kickstart/samples/tree/master/directives) [](/graphql-java-kickstart/samples/tree/HEAD@{2020-05-19T09:01:57Z}/directives)

I gave that approach a shot first, I do like the idea of expressing constraints (perhaps not all of them) in the schema for visibility. It turned out that the experience of implementing constraint validations through directive was not that great. Applying multiple constraints seemed tricky, and each constraint would need to be transformed to its own scalar - no?

> There's also a validators library from the graphql-java guys. Last time I checked there was an issue with it in certain cases though, not sure if it's fixed now: graphql-java/graphql-java-extended-validation.

I really don't want to have a dependency on a 3rd party package to do constraint validation. I also remember seeing this package having some compatibility issues and some things being "technically not possible yet" (something something nested validation IIRC).

Java (Bean) validation is a very standardized method for doing constraint validation. It's supported by most web frameworks. I'd argue it's a very core tool for Java developers when building domain models. One of the selling points of graphql-java-tools is that it's easy to plug in to existing RESTful services (which I could not agree more with, very good job with this project 👏). The only missing piece we're seeing is native support for constraint validation.

**Comment by oliemansm** [comment]
Well argued :)

Not sure when we will have time to take a look at this though, so it might take a while. We do encourage contributions in case you'd want to help out.

**Comment by williamboman-pp** [comment]
> Not sure when we will have time to take a look at this though, so it might take a while. We do encourage contributions in case you'd want to help out.

![](https://i.giphy.com/media/g0JP0HG6zF0o8/200w.webp)

I might just do that :)

**Comment by VsevolodGolovanov** [comment]
With Spring Boot you could just Autowire your Validated resolver into the GraphQL servlet and give it to the schemaParserBuilder as usual. The resolver would be proxied and validation will happen when it's invoked. Seems to work fine with 6.2.0.

Is first party support in Tools necessary when Spring (and CDI?) already make this possible?

**Comment by vojtapol** [comment]
@VsevolodGolovanov In general Tools should not have any consideration for Spring as it's meant to be used outside of Spring as well.

**Comment by benmccann** [comment]
I don't think this ticket is related to Spring, but rather about the `javax.validation.constraints` package, so maybe this issue should be reopened?
