### ISSUE TITLE
Argument de-serialization (Mapping) Problem

### ISSUE THREAD

**Issue by stevelaclasse** [graphql-java-kickstart/graphql-java-tools#401]
Hi,
i am Using Graphql-java with Resolvers and Database and i am facing a Problem with the argument that are passed as Input.
The Input Type have many arguments and two arguments are always set to Null and i don't know why, because those two arguments have values.
and in the response one of the argument is missing in the JSON output, in the Code i see that argument when i print the Response variable.
that is why i wanted to know who Json are transformed into POJO and POJO into Json.
Thanks.

**Comment by stevelaclasse** [comment]
in the Debug, i have seen a list called MergedFields with all fields and values i have used, then there is anoter list called SelectionSet which have all the above fields on the MergedFields execpt One, i don't know why one field (StringValue)is set to null an the other just ignored in the selection.

**Comment by vojtapol** [comment]
Can you put together a reproducible example? This library uses Jackson to map the input objects to Java types. It may be an issue of Jackson configuration. Note that you can provide custom Jackson mapper or custom configuration for the mapper when initially parsing the schema.

**Comment by stevelaclasse** [comment]
i dont know how i could provide an example, but i am interessed on the custom configuration of jackson.
note that i dont use datafetchers, but resolvers (that may used datafetchers).
thanks for your quick response

**Comment by vojtapol** [comment]
```java
SchemaParser.newParser()
    .schemaString(schemaString)
    .resolvers(resolvers)
    .options(SchemaParserOptions.newOptions()
        .objectMapperConfigurer(...) // to configure the default mapper
        .objectMapperProvider(...) // to provide your own mapper
        .build())
    .build()
    .makeExecutableSchema();
```

**Comment by stevelaclasse** [comment]
type user {
id:String!
name:String !
field1:String
field2:String
field3:String
field4:String
}

input userInput {
name:String !
field1:String
field2:String
field3:String
field4:String
}

mutation {
createUser(newuser: userInput!):User

in this example field3 and field4 are always set to null when the have values and in the response i don't see field 4.

**Comment by stevelaclasse** [comment]
> 
> 
> ```java
> SchemaParser.newParser()
>     .schemaString(schemaString)
>     .resolvers(resolvers)
>     .options(SchemaParserOptions.newOptions()
>         .objectMapperConfigurer(...) // to configure the default mapper
>         .objectMapperProvider(...) // to provide your own mapper
>         .build())
>     .build()
>     .makeExecutableSchema();
> ```

i don't use the SchemaParser, i just use a Datafetcher in some Directives to control some authentication values.

**Comment by stevelaclasse** [comment]
the problem was with Jakson, it didn't accept some variables name, i printed the Jackson Map to see which variable name he proposed and was checking for (for my case i was using the variable name "**aGoodName**" and jakson wanted "**agoodName**"), so i have just changed it like he wanted and everything works fine.
