### ISSUE TITLE
Upgrade to grahql-java 15.0

### ISSUE THREAD

**Issue by marceloverdijk** [graphql-java-kickstart/graphql-java-tools#405]
`graphql-java-tools` is not compatible with latest `graphql-java` `15.0`.

https://github.com/graphql-java-kickstart/graphql-java-tools/blob/e4690db3475889b1b32ad674d3ace48e5192875a/src/main/kotlin/graphql/kickstart/tools/TypeClassMatcher.kt#L87

`ScalarInfo.STANDARD_SCALAR_DEFINITIONS` does not exist in `graphql-java` `15.0` anymore.

**Comment by vojtapol** [comment]
`graphql-java-tools` defines dependency on the compatible version of `graphql-java`. Do not specify dependency on `graphql-java` separately to ensure everything works correctly.

**Comment by marceloverdijk** [comment]
I understand. For me this issue is mainly to track the upgrade to `15.0`.
