### ISSUE TITLE
Circular input property leads to stackoverflow

### ISSUE THREAD

**Issue by KammererTob** [graphql-java-kickstart/graphql-java-tools#409]
After updating graphql-java-tools to 6.1.0 i have encountered a stackoverflow exception on startup. I think that the problem was introduced in this commit: https://github.com/graphql-java-kickstart/graphql-java-tools/commit/10ee43f3e00f25194323a6ab7c1a9a4481726ca6 and happens because of the interaction between `determineInputType` and `createInputObject`. 
Example schema:

```
input A {
    id: ID!
    b: B
}

input B {
   id: ID!
   a: A
}
```

According to the spec this should be allowed (https://github.com/graphql/graphql-spec/pull/445, https://github.com/graphql/graphql-spec/issues/189), which leads me to believe that this is a bug.

**Comment by vojtapol** [comment]
Confirmed bug. Contributions welcome.

**Comment by enriquedacostacambio** [comment]
fyi, simple (non-mutual) recursion also triggers the bug:
```gql
input CriterionInput {
    and: [CriterionInput!]
    or: [CriterionInput!]
    not: CriterionInput
    status: StatusCriterionInput
}

input StatusCriterionInput {
    eq: String
}
```

**Comment by PhilippS93** [comment]
Can confirm. This is especially important for filtering purposes like recursive OR and AND patterns.
