### ISSUE TITLE
How do I throw an  RuntimeException instead of GraphQL error message

### ISSUE THREAD

**Issue by wxy0724** [graphql-java-kickstart/graphql-java-tools#417]
In my Java project, When a runtime exception occurs, I want to throw the custom exception instead of error.message.What should I do?

**Comment by vojtapol** [comment]
This would be better question for https://github.com/graphql-java/graphql-java as `graphql-java-tools` does not do anything special regarding handling errors nor executing queries.

GraphQL Java catches all exceptions and puts them into `GraphQLExecutionResult`. You can then rethrow them like this:

```java
ExecutionResult executionResult = graphQL.execute(executionInput);
GraphQLExecutionResult graphQLExecutionResult = new GraphQLExecutionResult(executionResult, context);
List<GraphQLError> errors = graphQLExecutionResult.getErrors();

for (GraphQLError error : errors) {
    if (error instanceof ExceptionWhileDataFetching) {
        throw ((ExceptionWhileDataFetching) error).getException();
    }
    // handle other types as needed
}
```
