### ISSUE TITLE
Unused type definitions are not visible in introspection queries

### ISSUE THREAD

**Issue by code-wok** [graphql-java-kickstart/graphql-java-tools#420]
If we define a type that is unused in the schema file e.g

```graphql
type User {
    ...
}

type Context {
    ...
}

type Query {
    user(id: ID!): User
}
```

- The `Query` and `User` types are returned from introspection queries but not `Context`. Is this by design?
- If it is by design, is there a way for the type to appear in introspection queries? I can see they appear in `SchemaParser.getUnusedDefinitions()` but is there a way to wire that in so that they are visible in introspection queries?

**Comment by vojtapol** [comment]
I don't believe the schema introspection should be returning unused types. Can you find specs or some other projects that do return unused types?

**Comment by williamboman-pp** [comment]
My use case to include unused types is for federation:

```kt
class QueryResolver : GraphQLQueryResolver {}

val schema = """
type User @key(fields: "uuid") @extends {
  uuid: ID! @external
  hasCompletedKyc: Boolean!
}

type Query {}
"""

var schema = SchemaParser.newParser()
  .schemaString(schema)
  .resolvers(QueryResolver())
  .build()
  .makeExecutableSchema()

schema = Federation.transform(schema)
  .resolveEntityType(...)
  .fetchEntities(...) // this will resolve the external User type we're extending
  .build()

println(SchemaPrinter().print(schema))
```

**Comment by seanscal** [comment]
@vojtapol @oliemansm could we get some eyes on these PRs? 🙂  - federation compatibility is critical in my company's framework evaluation, the library looks great - would be great to see this feature working
