### ISSUE TITLE
Create a new release supporting graphql-java 15.0

### ISSUE THREAD

**Issue by jflorencio** [graphql-java-kickstart/graphql-java-tools#423]
https://github.com/graphql-java-kickstart/graphql-java-tools/pull/413 seems to have made the required changes to graphql-java-tools to support graphql-java 15.0, but there hasn't been a new release with that PR. Would it be possible to cut a new release, or is there some issue blocking it?

**Comment by BiggestO** [comment]
Yes, if you could do this it would be greatly appreciated! :)

**Comment by vojtapol** [comment]
https://github.com/graphql-java-kickstart/graphql-java-tools/releases/tag/6.2.0

**Comment by BiggestO** [comment]
Excellent, thank you for the good work!
