### ISSUE TITLE
Invalid schema definition at build time when using the @connection directive

### ISSUE THREAD

**Issue by VsevolodGolovanov** [graphql-java-kickstart/graphql-java-tools#427]
The `@connection` directive is convenient, but requires you to use a type that's undeclared at build time, which can prompt your IDE or other tooling to consider it an error:
![image](https://user-images.githubusercontent.com/8070317/91178631-13fa5800-e6ee-11ea-8ae0-061678c83dec.png)

As the documentation says, at runtime:
> The connection type will be created if absent 

I don't want to give up build time validation. I wish GQLJT would (optionally?) overwrite the type even if it's present, so that I could provide a dummy definition:
![image](https://user-images.githubusercontent.com/8070317/91178317-a3533b80-e6ed-11ea-9a2c-062a4b8975fd.png)

(Using Intellij IDEA with the JS GraphQL plugin.)

**Comment by VsevolodGolovanov** [comment]
Maybe this could be solved some other way? Sidestep mentioning the type name at all?

**Comment by vojtapol** [comment]
The way we worked around this was to defined one dummy type `type Connection` that we use for all connections and the directive overrides it.

**Comment by VsevolodGolovanov** [comment]
@vojtapol, you're saying that if I do
```
gnarls(...): DummyConnection @connection(for: "Gnarl")

type DummyConnection {
}
```
Tools would generate the type `GnarlConnection` and redefine the query to return it at runtime:
```
gnarls(...): GnarlConnection @connection(for: "Gnarl")
```

That's not what happens. Tools leaves the query as is, returning `DummyConnection`, and doesn't generate a connection type, since `DummyConnection` is already defined.
