### ISSUE TITLE
Sorting a result collection

### ISSUE THREAD

**Issue by onewildgamer** [graphql-java-kickstart/graphql-java-tools#428]
Hi, I'm trying to find a way to sort a list of resulting collections after resolving the fields of each of the collection type's field.

The catch here is that the fields are fetched from different datasources (REST or DB). A rough example is,

```graphql
query PersonQuery {
    person(id: ID): Person
}

type Person {
    id: ID!
    name: String
    createdDate: DateNoTime
    relatives: [Relative]
}

type Relative {
    id: ID!

    " this data is stored in one service"
    name: String

    " this data is stored in another service"
    createdDate: DateNoTime

    " this data is stored in yet another service"
    relation: String
}
```

I have resolvers like so

```java
public class QueryResolver implements GraphQLQueryResolver {
    public PersonInput person(String id) {
        PersonInput input = new PersonInput();
        input.setId(id);
        return input;
    }
}

public class PersonResolver implements GraphQLResolver<PersonInput> {

    @Inject
    DataFetcher dataFetcher;

    public String name(PersonInput input) {
        return dataFetcher.getName(input);
    }

    public String createdDate(PersonInput input) {
        return dataFetcher.getCreationDate(input);
    }

   // here's the partially populated Relative class which only has id and name
    public List<Relative> relatives(PersonInput input) {
        List<Relative> partiallyFilledRelatives = dataFetcher.getPartialRelatives(input);
        return partiallyFilledRelatives;
    }
}

public class Relative {
    // relative id
    String id;
    String name;
    public getName() { return name; }
    public setName(String name) { this.name = name; }
    public getId() { return id; }
    public setId(String id) { this.id = id; }
}

public class RelativeResolver implements GraphQLResolver<Relative> {

    @Inject
    AnotherDataFetcher anotherDataFetcher;

    public LocalDate createdDate(Relative relative) {
        return anotherDataFetcher.fetchCreatedDate(relative.getId());
    }

    public String relation(Relative relative) {
        return anotherDataFetcher.fetchRelation(relative.getId());
    }
}
```

Now, as per the understanding, the `RelativeResolver` will be called for each of the `partiallyFilledRelatives` returned in the `PersonResolver::relatives` method and the returning collection will be sent in the response.

I am trying to find a way to sort the returned collection by `createdDate`. I for one, can iterate over the `partiallyFilledRelatives` to fetch the `createdDate` and sort it in `PersonResolver`. But, it seems like a hack.

I checked several forums regarding this, couldn't find any solution. Please suggest an idiomatic way to do this. And/or some better hacks :) if I don't have any other option.

**Comment by vojtapol** [comment]
Basically it boils down to the fact that at the time of resolving the `relatives` field you need to know the `createdDate` field on each of the items in the list. There is no other option than to front-load this and fetch all the necessary data in `PersonResolver`. Otherwise, by the time the `createdDate` is being resolved in `RelativeResolver` it is too late to change the order of the enclosing list.

It might look inefficient but I don't see a better way. If you think about it, even if the client does not request the `createdDate` field, they are *implicitly* requesting it by obtaining the `relatives` list in the correct order.

**Comment by onewildgamer** [comment]
Right, I was wondering if there are sorting options post all the field resolutions by sending a preferred comparator and sort order. i.e. once the list is prepared but just before sending the response to the client.

Also, I am new to the graphql technology, so I am unaware if such a thing is supported in the graphql schema or through directives or if it should be implemented in the supporting tools. Point me in the right direction, I can contribute on this feature tooling.

**Comment by onewildgamer** [comment]
I found these articles mentioning the support in various javascript frameworks,

[https://dev.to/mikewheaton/sorting-by-created-date-with-graphql-and-prisma-318c](https://dev.to/mikewheaton/sorting-by-created-date-with-graphql-and-prisma-318c)
[https://www.gatsbyjs.com/docs/graphql-reference/#sort](https://www.gatsbyjs.com/docs/graphql-reference/#sort)

**Comment by vojtapol** [comment]
I don't think this is in the scope of this library. Ideally, we will provide pluggable resolvers when you can both pre-process and post-process the method call, and then you could implement the sorting yourself.

In the mean time, if you are using Spring, you could use AOP for that.
