### ISSUE TITLE
GraphQLResolver接口能继承一下官方的接口吗？不兼容真的很难受

### ISSUE THREAD

**Issue by nerverbe** [graphql-java-kickstart/graphql-java-tools#430]

**Comment by mxmlnglt** [comment]
*... needs translation...*

**Comment by williamboman-pp** [comment]
> Can the GraphQLResolver interface inherit the official interface? Incompatibility is really uncomfortable

Not sure what this could mean? Which official interface @nerves?

**Comment by nerverbe** [comment]
sorry, it was a big mistake
