### ISSUE TITLE
java.lang.IllegalArgumentException: value already present - when trying to use the same class for input and output

### ISSUE THREAD

**Issue by VsevolodGolovanov** [graphql-java-kickstart/graphql-java-tools#440]
I'm trying to use the same class for input and output, but getting a problem with BiMap in SchemaClassScanner.

Here's the reproducer: https://github.com/VsevolodGolovanov/graphql-java-tools/commit/0526559dc4b3a8093ba29a8ddbd9d02189207019

(Why use the same class? Because it's just CRUD. Would be weird if it *weren't* the same class.)

**Comment by VsevolodGolovanov** [comment]
I actually was trying to make a reproducer for #216 which is the issue I'm currently getting in my real code ("Expected type 'XXX' to be a GraphQLInputType, but it wasn't!..."), but instead got this.

**Comment by vojtapol** [comment]
I use similar structure in my projects and it works. I wonder what's different here 🤔.

**Comment by VsevolodGolovanov** [comment]
![image](https://user-images.githubusercontent.com/8070317/93870435-e77a3180-fcd5-11ea-8a52-c884699bf2c9.png)
Nevermind.
