### ISSUE TITLE
Upgrade to GraphQL-Java 16.0

### ISSUE THREAD

**Issue by timward60** [graphql-java-kickstart/graphql-java-tools#457]
[GraphQL-Java](https://github.com/graphql-java/graphql-java) just recently updated their latest version to [16.0](https://github.com/graphql-java/graphql-java/releases/tag/v16.0) [announcement](https://spectrum.chat/graphql-java/general/graphql-java-16-0-has-been-released~cfe92d47-cb2a-4a9d-adfb-a40c9d0b5646).

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

## Description

Upgrade this library to support the latest GraphQL-Java version.

### Use Cases

Provides the latest features provided by GraphQL-Java.

**Comment by timward60** [comment]
I tried updating in my private fork ([draft-PR](https://github.com/graphql-java-kickstart/graphql-java-tools/pull/458)) and there seems to be two obvious breaking changes that impact this library:

- [X] SchemaParserBuilder was catching `org.antlr.v4.*` exceptions (`ParseCancellationException`, `RecognitionException`) thrown by graphql.parser.Parser. This has now been replaced by an explicit GraphQL exception `InvalidSyntaxException`.
   This change seems simple enough to make without much impact.

- [ ] graphq.schema.idl.SchemaGeneratorHelper#buildDirective has been marked package private. This seems like a major breaking change. I am still digging into the code to understand exactly how it is used and how it would be possible to move away from using this internal type. Any background context on this usage and suggestions?

There are some new features but haven't looked at whether there are any required changes in this library to expose them.

**Comment by oliemansm** [comment]
@timward60 Thanks for taking the effort to try to make it compatible with the latest version of GraphQL-Java!

That class is notorious actually. In the end we copied the version of that class over to this library a while ago, but this might mean they updated it and you need to update it. The local copy in this library is in the `graphql.kickstart.tools.directive` package. Hope that helps.

**Comment by timward60** [comment]
Are you referring to `graphql.schema.idl.SchemaGeneratorDirectiveHelper`? The file with the breaking change is `graphql.schema.idl.SchemaGeneratorHelper`.

I tried using the same approach of making a copy of this helper class, but it depends on the following public API classes with package-private constructors:`FieldWiringEnvironment`, `ScalarWiringEnvironment`, `InterfaceWiringEnvironment`, `UnionWiringEnvironment`. There is also a dependency on `SchemaExtensionsChecker.gatherSchemaDirectives` which is marked package-private.

**Comment by UkonnRa** [comment]
Yes, I met the same error:

```
java.lang.NoSuchMethodError: 'graphql.schema.GraphQLDirective graphql.schema.idl.SchemaGeneratorHelper.buildDirective(graphql.language.Directive, java.util.Set, graphql.introspection.Introspection$DirectiveLocation, graphql.schema.GraphqlTypeComparatorRegistry)'
	at graphql.kickstart.tools.SchemaParser.buildDirectives(SchemaParser.kt:317)
	at graphql.kickstart.tools.SchemaParser.createField(SchemaParser.kt:292)
	at graphql.kickstart.tools.SchemaParser.access$createField(SchemaParser.kt:23)
	at graphql.kickstart.tools.SchemaParser$createObject$$inlined$forEach$lambda$1.apply(SchemaParser.kt:138)
	at graphql.kickstart.tools.SchemaParser$createObject$$inlined$forEach$lambda$1.apply(SchemaParser.kt:23)
	at graphql.schema.GraphQLObjectType$Builder.field(GraphQLObjectType.java:335)
	at graphql.kickstart.tools.SchemaParser.createObject(SchemaParser.kt:137)
	at graphql.kickstart.tools.SchemaParser.parseSchemaObjects(SchemaParser.kt:83)
	at graphql.kickstart.tools.SchemaParser.makeExecutableSchema(SchemaParser.kt:112)

```

Any idea?
