### ISSUE TITLE
java.lang.NoSuchFieldError: STANDARD_SCALAR_DEFINITIONS upon building schema in Eclipse VertX project

### ISSUE THREAD

**Issue by vinaybedre** [graphql-java-kickstart/graphql-java-tools#469]
## Description
When I am building schema parser, I get the following error `java.lang.NoSuchFieldError: STANDARD_SCALAR_DEFINITIONS`
The project is based on Eclipse Vertx [https://vertx.io/](url)

### Expected behavior
The schema parser when given file(s) and resolvers, throws error as given above.

### Actual behavior
The schema parser when given file(s) and resolvers, should build the schema without errors.

### Steps to reproduce the bug

1. Clone the repo https://github.com/vinaybedre/graphql-java-tool-vertx
2. Start vertx server by running `./gradlew run`

**Comment by ind4** [comment]
There was a version mismatch.
following dependency worked for me (in build.gradle)
```
implementation("com.graphql-java:graphql-java:16.1")
implementation("com.graphql-java-kickstart:graphql-java-tools:6.3.0")
```

**Comment by vojtapol** [comment]
It is not recommended to specify version of any other dependency than `graphql-java-tools`. That way you can be sure the libraries are always compatible.
