### ISSUE TITLE
v11.0.3 contains a new version of graphql-java that contains breaking changes...perhaps v12 should be released instead?

### ISSUE THREAD

**Issue by bsara** [graphql-java-kickstart/graphql-java-tools#587]
v11.0.3 of this lib updated to use v17.2 of graphql-java. That version of graphql-java contains breaking changes. This creates issues with dependency resolution when one is using the same version numbers across the graphql kickstart libs. It seems that perhaps a v12 of this lib should be released and a v11.1.3 that reverts back to the previously used version of graphql-java?

**Comment by oryan-block** [comment]
We are now on v12.0.1
