### ISSUE TITLE
Files licensed under ORACLE PROPRIETARY/CONFIDENTIAL.

### ISSUE THREAD

**Issue by naufalkhalid** [graphql-java-kickstart/graphql-java-tools#676]
Most of the files are licensed under MIT. This file (graphql/kickstart/tools/util/ParameterizedTypeImpl.java) is licensed under ORACLE PROPRIETARY/CONFIDENTIAL. Is there any specific reason for that?

**Comment by oryan-block** [comment]
This appears to have been copied over from the JDK after the this class became inaccessible to outside modules. We should probably create our own implementation of `ParameterizedType`.
