### ISSUE TITLE
Implement graphql.schema.LightDataFetcher

### ISSUE THREAD

**Issue by adrian-skybaker** [graphql-java-kickstart/graphql-java-tools#732]
[graphql-java 20.0](https://github.com/graphql-java/graphql-java/releases/tag/v20.0) introduced the concept of a lightweight data fetcher, to reduce the amount of redundant `DataFetchingEnvironment` objects wastefully created when just calling simple object properties.

Ideally graphql.kickstart.tools.resolver.TrivialMethodFieldResolverDataFetcher would implement this, to make use of the internal optimisations in graphql-java.

**Comment by oryan-block** [comment]
Done in https://github.com/graphql-java-kickstart/graphql-java-tools/pull/788
