### ISSUE TITLE
 graphqls file with at least 15000 tokens - What is config to fix 

### ISSUE THREAD

**Issue by dineshawa** [graphql-java-kickstart/graphql-java-tools#759]
I am using graphql-java-tool 13.0.3 and getting error "More then 15000 grammar tokens have been presented" How to increase more then 1500 in springboot config or Code . Please suggest .

**Comment by dineshawa** [comment]
Error : Invalid Syntax : More than 15000 grammar tokens have been presented. To prevent Denial Of Service attacks, parsing has been cancelled. offending token '<EOF>' at line 1 column 179655   
I am looking soltion how to incease token size from config or code.

**Comment by dineshawa** [comment]
Using latest jar :
implementation ('com.graphql-java-kickstart:graphql-java-tools'){
version {
strictly "13.0.3"
}
}

**Comment by oryan-block** [comment]
This is not related to graphql-java-tools. Please refer to https://github.com/graphql-java/graphql-java/pull/2549

**Comment by dineshawa** [comment]
I need to allow more then 15000 tokens but not seeing any option to change in config or code for com.graphql-java-kickstart:graphql-java-tools @oryan-block
